### ISSUE TITLE
Add Microsoft Visual Studio logo

### ISSUE THREAD

**Issue by ismaelgasparin** [gilbarbara/logos#10]
Please? :)

![Short](https://upload.wikimedia.org/wikipedia/commons/e/e4/Visual_Studio_2013_Logo.svg)

![Full](https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Visual_Studio_2012_logo_and_wordmark.svg/1280px-Visual_Studio_2012_logo_and_wordmark.svg.png)

**Comment by julianocomg** [comment]
Microsoft copyright lawyers gonna love this :sun_with_face:

**Comment by ismaelgasparin** [comment]
:O

**Comment by julianocomg** [comment]
Hey I was just kidding!!
