### ISSUE TITLE
IEEE logo

### ISSUE THREAD

**Issue by cpustar** [gilbarbara/logos#100]
It would also be nice to have the Institute of Electrical and Electronics Engineers logo:

![Image of IEEE](https://www.ieee.org/ucm/groups/public/@ieee/@web/@org/@globals/documents/images/ieee_logo_mb_tagline.gif)
![Image of IEEE](http://ewh.ieee.org/sb/kerala/gecb/image/ieee_logo.gif)

**Comment by gilbarbara** [comment]
Added 3dc9ab686332bf287dc4ec50de4b072c503173ff
Thanks
