### ISSUE TITLE
Add Sublime Text logo

### ISSUE THREAD

**Issue by ismaelgasparin** [gilbarbara/logos#11]
Please? :)

![logo](https://upload.wikimedia.org/wikipedia/en/4/4c/Sublime_Text_Logo.png)

**Comment by gilbarbara** [comment]
I couldn't find this in vector/svg yet. I'll try again soon.

**Comment by joeriharleman** [comment]
The home page actually has the .svg

https://www.sublimetext.com/
https://www.sublimetext.com/images/logo.svg

**Comment by gilbarbara** [comment]
Added in c122ccfcfdb15d9958a85696ff2460ac3b01f8ca
Thanks
