### ISSUE TITLE
WebPlatform Logo optimized

### ISSUE THREAD

**Issue by watersb** [gilbarbara/logos#110]
I optimized the WebPlatform.org logo, 897 bytes.

https://raw.githubusercontent.com/watersb/watersb.github.io/master/img/svg/logos/WebPlatform%20Logo.svg

**Comment by gilbarbara** [comment]
hello!
Thanks for the link but I'm not really worried about file size for the logos in this repo.
You could use a tool like [svgo](https://github.com/svg/svgo) if you really need to optimize any of these in your build process.

[s]
