### ISSUE TITLE
New logo request

### ISSUE THREAD

**Issue by gokaygurcan** [gilbarbara/logos#113]
I know i'm asking too much, but it's good to have all these logos in one place imho. Here comes the new requests. Thanks in advance ;)

- [x] Turret - [homepage](http://bigfishtv.github.io/turret/) - see note 1
- [ ] Demandware - [png](https://upload.wikimedia.org/wikipedia/en/0/0f/Demandware_Logo.png)
- [x] Olapic - [jpg](http://beatcreativemarketing.com/wp-content/uploads/2014/03/Olapic-logo.jpg)
- [ ] Gandi.net - [press page](https://www.gandi.net/press/)
- [x] Namecheap - [eps, download](https://namecheap.simplekb.com/SiteContents/2-7C22D5236A4543EB827F3BD8936E153E/media/namecheap-logo-brand-external.zip)
- [ ] Godaddy - [press page](https://aboutus.godaddy.net/newsroom/media-resources/default.aspx#_ctrl0_ctl84_divModuleContainer)
- [x] Open cart - [ai, download](http://seeklogo.com/opencart-logo-192799.html)
- [x] Aurous - [press kit, download](https://aurous.me/Press%20Kit.zip)
- [x] INK - [png](https://cloud.githubusercontent.com/assets/1509413/10480101/06b93572-7271-11e5-9f6c-af32bf89a081.png) (page http://ink.sapo.pt/)
- [x] Bitnami - [about page](https://bitnami.com/about-us/logos)
- [x] XAMPP - [svg](https://upload.wikimedia.org/wikipedia/commons/0/03/Xampp_logo.svg)
- [x] PushBullet - [press page](https://www.pushbullet.com/press)

Notes: 
1 - 
```html
<svg class="home-header-icon" xmlns="http://www.w3.org/2000/svg" width="44" height="64" viewBox="0 0 44 64">
	<path fill="#FFFFFF" d="M36.7 52l-3.1-28.1 8.4-6v-17.9h-8v7h-6v-7h-12v7h-6v-7h-8v17.9l8.4 6-3.1 28.1h-7.3v12h44v-12z"/>
</svg>
```

**Comment by gilbarbara** [comment]
Added a few in 6a2abfc3912d7376d3164073586c9693f04e3e5c

**Comment by gokaygurcan** [comment]
You're the best! Thanks.

**Comment by gilbarbara** [comment]
Some more 75738e9781a30a9b45d10315e4aabf96d003c886
Thanks
