### ISSUE TITLE
Foundation Logo

### ISSUE THREAD

**Issue by jlnabais** [gilbarbara/logos#117]
Foundation website:

http://foundation.zurb.com/

LOGO:

http://foundation.zurb.com/assets/img/support/goodies/why-the-yeti.svg

**Comment by gilbarbara** [comment]
hey,
The Foundation/Yeti logo is already online.

**Comment by jlnabais** [comment]
My bad, Search isn't retrieving any result when I search for "Foundation".
Thanks!

**Comment by gilbarbara** [comment]
yeah, just saw that, I'll fix it soon!
