### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by rctneil** [gilbarbara/logos#126]
How about Telegram: https://telegram.org/

**Comment by limenet** [comment]
SVG: https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg

**Comment by sergeysova** [comment]
Is project alive?

**Comment by gilbarbara** [comment]
@sergeysova Yes

**Comment by gilbarbara** [comment]
Added in 8105552754167524dc5dff22c66f4ac8d9de1ca5
Thanks
