### ISSUE TITLE
Hoa logo

### ISSUE THREAD

**Issue by Hywan** [gilbarbara/logos#137]
Hello :-),

Hoa is a set of PHP libraries, used by major companies and projects world-wide (see http://hoa-project.net/). It has been downloaded more than 1,3 million times so far.

We request to have our SVG logo on svgporn.com :-). Here is the link, http://static.hoa-project.net/Image/Hoa.svg:
![Hoa's logo](http://static.hoa-project.net/Image/Hoa.svg).

The file has been already optimized by hand. If you are able to do better, please, tell us! We can help too.

**Comment by gilbarbara** [comment]
Hello!

Added 081a89a93b6af2bba5cf4eeace7a5c430785c003
:+1:

**Comment by Hywan** [comment]
Thanks!
