### ISSUE TITLE
Where are Apple, Microsoft and Oracle? Any prejudice?

### ISSUE THREAD

**Issue by ezequias** [gilbarbara/logos#14]
All my questions are on the subject.

**Comment by gilbarbara** [comment]
hey!

Not at all. But so far I'm just collecting logos related to development.
There are a bunch of site with major brands logos. Ex: [brands of the world](http://www.brandsoftheworld.com/)

**Comment by ezequias** [comment]
Nice but I just found eps and ai files and not SVGs
