### ISSUE TITLE
twitch.tv logo

### ISSUE THREAD

**Issue by runningskull** [gilbarbara/logos#140]
This collection is killer. Thanks for the hard work.

It would be great to see the [Twitch.tv](http://twitch.tv) logo as well. Brand assets are at http://www.twitch.tv/p/brandassets -- they offer pdf's of the logotype & mark.

cheers!

**Comment by denilsonsa** [comment]
FYI, I have the [Twitch logo](https://github.com/denilsonsa/denilsonsa.github.io/blob/master/icons/Twitch.svg) in [my own collection](https://github.com/denilsonsa/denilsonsa.github.io/tree/master/icons). As with any other logo that I've created or converted, feel free to reuse freely. :)

**Comment by gilbarbara** [comment]
Added 081a89a93b6af2bba5cf4eeace7a5c430785c003
Thanks @runningskull and @denilsonsa
