### ISSUE TITLE
Codecept logo

### ISSUE THREAD

**Issue by gokaygurcan** [gilbarbara/logos#141]
Hey mate, it's me again. 
This time it's only one logo ;)

webpage: http://codecept.io/
logo: http://codecept.io/images/cjs-base.png

Thanks in advance.

**Comment by gilbarbara** [comment]
Hey!

I added codeception logo. I couldn't find a vector file of it, yet.

**Comment by gokaygurcan** [comment]
Thanks a lot. 
I also checked it on the web but no success. Will ping you if I find something.
