### ISSUE TITLE
Giant Swarm

### ISSUE THREAD

**Issue by marians** [gilbarbara/logos#147]
- http://styleguide.io/giantswarm/logo_standard/giantswarm_logo_standard.svg
- http://styleguide.io/giantswarm/logo_simplified/giantswarm_logo_simplified.svg

**Comment by marians** [comment]
Thanks for adding the bant (that's how we call the little bee/ant) at Giant Swarm.

The eyes got displaced a bit though.

![image](https://cloud.githubusercontent.com/assets/273727/13699596/9c62edfa-e77b-11e5-9313-d32cb0cd486c.png)

Right:

![image](https://cloud.githubusercontent.com/assets/273727/13699605/b11a0850-e77b-11e5-8675-ec30c48553c8.png)

**Comment by gilbarbara** [comment]
Oops!
Fixed in 0f758a2595496879e00cd7925abdf1833abae566

Thanks

**Comment by marians** [comment]
Thank you!
