### ISSUE TITLE
Shipit.js

### ISSUE THREAD

**Issue by manuelbieh** [gilbarbara/logos#155]
I have already made a pull request but now I have seen that you don't accept pull requests.

The logo can be found here: https://github.com/shipitjs/shipit but I already added a svg version of the logo to the pull request which is this one https://github.com/gilbarbara/logos/pull/152

**Comment by gilbarbara** [comment]
hey,
I'll add it in the next batch!

Thanks

**Comment by gilbarbara** [comment]
Added 8d79fa158736a6a68713c96974b9a611b713bd4d
:)
