### ISSUE TITLE
minify with SVGOMG

### ISSUE THREAD

**Issue by tomByrer** [gilbarbara/logos#158]
https://jakearchibald.github.io/svgomg/ (defaults work fine; no discernible difference)
Saves 20-45% file size, even after gzip.  I could also find value with having an archive of non-minified SVG.  So to prevent any dependencies having to rewrite code (since likely deployed code will want to consume smallest files, only in editing one *may* need the source), I suggest move `/logos` to `/src` & put minified files back into `/logos`.

Nice archive; I'd like to host on a CDN after this is done when I get a chance.

**Comment by gilbarbara** [comment]
Thanks @tomByrer 😁

But this repo isn't about minification. There are plenty of tools to minify SVG in the build/production process and I always use svgo in my other projects.

Feel free to clone the repo and host the minified versions if you want to!

[s]
