### ISSUE TITLE
svgporn API

### ISSUE THREAD

**Issue by soulchild** [gilbarbara/logos#161]
Is there an API for svgporn.com or is the meta-data (name, tag, categories, etc.) available in a machine-friendly format (JSON) somewhere?

**Comment by gilbarbara** [comment]
Hey,
Yeah, there's [this](https://github.com/gilbarbara/logos/blob/app/app/logos.json) one I'm using with the front-end. 

I'll add it to master in my next update.

**Comment by soulchild** [comment]
Cool, thanks a lot!

**Comment by ruchern** [comment]
@gilbarbara Hi, I tried to access the API of this SVGs and the link seemed to be brojen.

**Comment by soulchild** [comment]
Don’t know if this helps, but I wrote my own [Logos API](https://github.com/soulchild/logos-api) which aggregates a couple of SVG logo repositories. Its main purpose is to power my [Sketch Logo Fetcher](https://github.com/soulchild/sketch-logo-fetcher/) plugin.

**Comment by gilbarbara** [comment]
@soulchild you shouldn't be using the firebase API link. I had some usage limit problems early this year and I'll lock it down.

**Comment by ruchern** [comment]
@soulchild thanks for that. I had a loon at it. It looks like it has to be ran on localhost only? 

I would prefer it to be a live API server. Is that possible? Both @soulchild and @gilbarbara

**Comment by soulchild** [comment]
@gilbarbara: My logos API project just clones your svgporn repository (among others) from Github and serves the logos itself. Or did I misunderstand your comment?

@ruchern: Yeah, you probably need to host the API yourself if you’re planning to offer some public services based on it. If you just need something to play around, you may use https://logos-api.funkreich.de. But please don’t depend on it - it may go done at any time without prior notice. See the documentation of the Logos API project for available endpoints.

**Comment by gilbarbara** [comment]
@soulchild you are using the non-public API endpoint here: https://github.com/soulchild/logos-api/blob/master/bin/update-logos#L18

**Comment by gilbarbara** [comment]
@ruchern There's no public API, only the repo

**Comment by ruchern** [comment]
@gilbarbara 

https://github.com/soulchild/logos-api/blob/993d68aba1cbce40e2d09ca1b1c1e85026351bbe/bin/update-logos#L18

This could work

**Comment by gilbarbara** [comment]
@ruchern You can't use that URL, is not public.

**Comment by ruchern** [comment]
@gilbarbara I see. Just let me know if there are any APIs that is in the pipeline or can I use that to create an API server, crediting back the original contents to you.

**Comment by gilbarbara** [comment]
No plans for a public API. Just this repo and https://svgporn.com
You can use the content of the master branch, no problem. I'll take down the rest tomorrow

**Comment by ruchern** [comment]
Okay thank you!

**Comment by soulchild** [comment]
Uh, I totally forgot about that. Thanks for the heads up, @gilbarbara. 

So, is there another (preferred) way to access the `items.json` file after you take the firebase db down? It‘s still not part of the GitHub repo in some form or another, is it? 

If not, I‘ll have to start using the SVG filenames instead, which probably is not going to totally degrade the quality of my API’s search results, but anyways...

I‘d love to continue the API for all the Sketch plugin users.

**Comment by ruchern** [comment]
@soulchild let's work on something using the `master` branch since the owner of the repo said it's fine doing that.

**Comment by soulchild** [comment]
I‘ll look into using the logo filenames instead of the data provided by the `items.json` file to keep the API working. We‘ll see how this impacts search results. Shouldn‘t be too bad, I suppose...

**Comment by gilbarbara** [comment]
Please don't paint me as the bad guy.
I've gathered and vectorized all these logos and made them available on this repo for everyone to use.

I've never planned to make a public API but you are free to create one and host it, as some people have done before.

However, the resources I use at svgporn.com are not part of this repo and not free to use.  
I'm already close to the rate and usage limits of my Firebase account and it's kinda expensive to upgrade.

**Comment by soulchild** [comment]
That was never my intention! I believe we all value the great work you‘re putting into this project. Thanks for that! I was just trying to find out if you had any plans to put the meta data into this repo as well, so that my Logos API could be kept as is. No worries, I‘ll figure something out! :)

**Comment by soulchild** [comment]
FYI, I just [committed](https://github.com/soulchild/logos-api/commit/bfa02e406ceb1d741573a3577ea9fe1bc9c7b5c0) a patch which does not depend on your Firebase API endpoint anymore.

**Comment by gilbarbara** [comment]
Thanks @soulchild 

I've added a JSON file with some of the data I use on SVGPorn, just the basics.
You can use this data and load the files with the CDN URL: `https://cdn.svgporn.com/logos/${item.files[0]}`

ex: React from the CDN

![React](https://cdn.svgporn.com/logos/react.svg)

**Comment by gilbarbara** [comment]
@ruchern you can fetch https://raw.githubusercontent.com/gilbarbara/logos/master/logos.json and load the files from the CDN too

**Comment by soulchild** [comment]
Cool, @gilbarbara! Are you planning on keeping this in sync with the actual SVG files in the repo?

@ruchern: The latest version has been updated to use the new `logos.json` file from the repo instead of the Firebase API.

**Comment by gilbarbara** [comment]
@soulchild yes
