### ISSUE TITLE
New Instagram icon (May 2016)

### ISSUE THREAD

**Issue by denilsonsa** [gilbarbara/logos#162]
[Instagram launched a new look](http://blog.instagram.com/post/144198429587/160511-a-new-look), a [very clean EPS can be found on their brand website](https://www.instagram-brand.com/), and [I've even converted it to SVG](https://github.com/denilsonsa/denilsonsa.github.io/commit/e1c9567cabf83189442ff99fb06b12e45cb5e5ed) ([I later changed the color back to black](https://github.com/denilsonsa/denilsonsa.github.io/commit/ff6a7c530fe13e78c62be7818e6ccee77840af03), after comparing with the PNG). Feel free to incorporate that SVG code into your collection! :)

**Comment by gilbarbara** [comment]
Done 2a2939b29ae8272d0157ce998a4d80ef7ddaab66
