### ISSUE TITLE
New: WebSocket Logo

### ISSUE THREAD

**Issue by Fylax** [gilbarbara/logos#169]
I created WebSocket Logo and I already optimized it.
Feel free to futher optimize it if you may.
Instead of link I just pasted it here as code (as it's only 317 bytes)

`<svg xmlns="http://www.w3.org/2000/svg"><style>#a{fill:#202020;stroke:#202020;}</style><path d="M382 227v126h63V201l-70-70 -45 45L382 227zM130 375l70 71h307l-62-62H226l-52-53L130 375zM309 197l21-21L222 68H4l62 62h130l46 45 -68 67 -45-45v-34H66v60l108 108 23-22 44 44h88l-88-89 23-23 87 88v-89L309 197z" id="a"/></svg>`

**Comment by gilbarbara** [comment]
hey,
What do you mean by websocket, the spec? Is it official?

**Comment by Fylax** [comment]
WebSocket protocol, RFC 6455.
Not 100% it's an official logo, but googling "websocket logo" reports this logo and a lot of framework report this logo as websocket logo, so it's safe to assume that.
On w3c logo creator (https://www.w3.org/html/) if you check "Connectivity / Realtime" (which is exactly what websocket does) you'll see it appearing

**Comment by gilbarbara** [comment]
Added 2a2939b29ae8272d0157ce998a4d80ef7ddaab66
Thanks
