### ISSUE TITLE
New: UpWork Logo

### ISSUE THREAD

**Issue by evanre** [gilbarbara/logos#175]
Hi, I'm not expert in Adobe Illustrator, and I'm sorry if there is wrong format according to your tips.
https://pressurgeons.com/img/upwork.svg
https://pressurgeons.com/img/upwork2.svg
https://pressurgeons.com/img/upwork3.svg

**Comment by gilbarbara** [comment]
Added in 0b0cbcf7f319a23e11d3424fe55eed088d9729b3
👍
