### ISSUE TITLE
Appveyor logo

### ISSUE THREAD

**Issue by torn4dom4n** [gilbarbara/logos#176]
Can you create appveyor logo?

Website: https://ci.appveyor.com
Logo: 
![appveyor-icon](https://cloud.githubusercontent.com/assets/16760489/17168673/e370b444-540d-11e6-9757-08f3ce6a362f.png)

**Comment by gilbarbara** [comment]
Added in f892a9d96fa1d68a350f988ef9b98b74b1ffc09c
Thanks
