### ISSUE TITLE
New: Front logo

### ISSUE THREAD

**Issue by eramdam** [gilbarbara/logos#179]
Hi,

I work for @Frontapp and here are the logo + logotype of the company.

- logo alone https://www.dropbox.com/s/y9n867weft56jz2/logo-alone.svg?dl=0
- logotype https://www.dropbox.com/s/n41vioimf64apy3/logotype.svg?dl=0

**Comment by gilbarbara** [comment]
Added in f892a9d96fa1d68a350f988ef9b98b74b1ffc09c
Thanks
