### ISSUE TITLE
GalliumOS logo

### ISSUE THREAD

**Issue by PurgingPanda** [gilbarbara/logos#186]
link to svg: https://github.com/GalliumOS/galliumos-distro/blob/master/artwork/logo/icon-color.svg

Greets,
PurgingPanda

**Comment by torn4dom4n** [comment]
I think it was completed, https://github.com/gilbarbara/logos/blob/master/logos/galliumos.svg!

**Comment by gilbarbara** [comment]
Oh yeah! Added in 78786426f5236eb1fb9db652fe87854bc94e873d
Thanks
