### ISSUE TITLE
Payment systems

### ISSUE THREAD

**Issue by evanre** [gilbarbara/logos#188]
[Visa](http://evanre.com/assets/img/Visa.svg)
[AmericanExpress](http://evanre.com/assets/img/AmericanExpress.svg)
[Discover](http://evanre.com/assets/img/Discover.svg)
[MasterCard](http://evanre.com/assets/img/MasterCard.svg)
[Stripe](http://evanre.com/assets/img/Stripe.svg)

**Comment by gilbarbara** [comment]
Stripe was updated in 78786426f5236eb1fb9db652fe87854bc94e873d

**Comment by gilbarbara** [comment]
Added in 31475e2deeef10cfaef03b6e17092e09ae6af757
