### ISSUE TITLE
Google AdSense and Google AdWords

### ISSUE THREAD

**Issue by torn4dom4n** [gilbarbara/logos#194]
Can you see **Google AdSense** and **Google AdWords** on **GitHub** and **SVGPORN**?

**Comment by gilbarbara** [comment]
Sorry, I'm not sure I understand your question. Are you asking If I can see those logos?

**Comment by torn4dom4n** [comment]
I can't see **Google AdSense** and **Google AdWords** on [SVGPORN](http://svgporn.com):
 
![ads](https://cloud.githubusercontent.com/assets/16760489/20698066/d4ebba9c-b630-11e6-84a5-a74dcc5734d5.png)

And when I open [Google Adsense](https://github.com/gilbarbara/logos/blob/master/logos/google-adsense.svg) and [Google Adwords](https://github.com/gilbarbara/logos/blob/master/logos/google-adwords.svg):

![googleadsense](https://cloud.githubusercontent.com/assets/16760489/20698116/46470930-b631-11e6-8953-62e8702c9f17.png)

**Comment by gilbarbara** [comment]
Yeah, I can see them in Chrome and Safari in the github page and svgporn.com
Which browser/version?

**Comment by torn4dom4n** [comment]
I use Chrome 54 on Windows 10 Aniversary 64bit.

**Comment by gilbarbara** [comment]
Fixed
