### ISSUE TITLE
logos.json

### ISSUE THREAD

**Issue by soulchild** [gilbarbara/logos#195]
Hi Gil,

first of all, I hope you don't mind me using your logos repository for my [logos-api](https://github.com/soulchild/logos-api) project , whose sole purpose is basically to power my [Sketch Logo Fetcher plugin](https://github.com/soulchild/sketch-logo-fetcher). 

I'm currently cloning the app-branch of your logos repo because it contains the logos.json and I have noticed that it hasn't been updated in a while. Is that branch abandoned and/or are there any plans on moving the logos.json over to the master branch?

Thanks and keep up the awesome work!

**Comment by gilbarbara** [comment]
Hey @soulchild 

I don't mind at all, I made this repo to have the logos easily available. 👍 

But I moved the collection from the static json file to a Firebase database and the logos are hosted  in AWS S3 now.
I've renamed the previous `app` branch to `app-old` and reused the name for the updated site with the new UI and hosting.

You can fetch it with the REST endpoint at: [items.json](https://logos-c87b5.firebaseio.com/items.json)

And the base URL for the SVGs is https://s3-us-west-2.amazonaws.com/svgporn.com/logos/
Loop the collection and append the base url to `files` array

[s]
