### ISSUE TITLE
Framework7

### ISSUE THREAD

**Issue by mblackritter** [gilbarbara/logos#217]
[Carlos Pinto](https://twitter.com/qroftcom) created a vector version some time ago ([Forums - Framework7 Logo](http://forum.framework7.io/#!/getting-started:framework7-logo)):

![Framework7 - SVG](http://www.seemiyah.com/framework7-logo-v1.svg)

But it seems the official logo got an update in the meantime (PNG):

![Framework7 - New Logo](https://cdn.framework7.io/i/logo-new.png)

**Comment by gilbarbara** [comment]
Couldn't find a vector file.

**Comment by mblackritter** [comment]
It's gone in the meantime, but the logo changed again anyway and can now be found as SVG on their site:

[https://framework7.io/i/logo.svg](https://framework7.io/i/logo.svg)

**Comment by gilbarbara** [comment]
Added in 84fc2abe2b9d0b5b39ceac4af32c6e7eccecd657
