### ISSUE TITLE
Add Pagekit logo

### ISSUE THREAD

**Issue by OliviaS** [gilbarbara/logos#221]
Pagekit is a new, modern Open Source CMS. It would be great to get the Pagekit logo included.

https://pagekit.com/storage/logos/pagekit-icon.svg

Thanks for consideration!

**Comment by gilbarbara** [comment]
I'll add it in the next update.

**Comment by gilbarbara** [comment]
Added in f4f0886337425dc331172c8b94e5f4e1af2f6e3e
Thanks
