### ISSUE TITLE
How about making all these logos into flat badges?

### ISSUE THREAD

**Issue by aleen42** [gilbarbara/logos#224]
![NASA](https://cdn.rawgit.com/aleen42/badges/master/src/nasa.svg)

![bitcoin](https://cdn.rawgit.com/aleen42/badges/master/src/bitcoin.svg)

I have an idea, and I have also created a repository for collecting badges in [this repository](https://github.com/aleen42/badges), which have tools to build. So, since I have seen so many logos with SVG formatting here, how about making them into badges, and add to the list? Like NASA, and Bitcoin above, they have been used to document in different projects.

**Comment by gilbarbara** [comment]
Hey!

I think this goes beyond the scope of this repo but if you want to make badges out of them feel free to use! 👍
