### ISSUE TITLE
Service workers

### ISSUE THREAD

**Issue by Crecket** [gilbarbara/logos#229]
Perhaps it'd be useful if you added a service worker to the website. Simply pre-caching the main css/js files to run the page with [sw-precache](https://github.com/GoogleChrome/sw-precache) and using [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) to cache any svg files that the user has viewed. 

Not only would it significantly improve performance for the initial pageload, it'd also turn the site into a PWA so mobile users can add it to their home screens.

**Comment by gilbarbara** [comment]
I'll definitely add a service worker in the next version.
However I think is too much to save the logos on the client machine...

**Comment by Crecket** [comment]
That is why I suggest using sw-precache to only store the main files. And then dynamically store any SVG images which the browser is already downloading anyways. I agree that there are too many SVG images to simply pre-cache everything on page-load

**Comment by gilbarbara** [comment]
done
