### ISSUE TITLE
Next.js Framework

### ISSUE THREAD

**Issue by jthegedus** [gilbarbara/logos#233]
https://github.com/zeit/next.js/

There is not SVG currently available. PNG [here](https://cloud.githubusercontent.com/assets/13041/19686250/971bf7f8-9ac0-11e6-975c-188defd82df1.png)

**Comment by flexbox** [comment]
In fact I added the `.svg` version in my PR 😉

**Comment by gilbarbara** [comment]
Added in f31807d0fcca18a2d2b498ad30da5c7b061c6049
Thanks
