### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by brunolemos** [gilbarbara/logos#247]
SVG square: 
[<img src="https://vignette.wikia.nocookie.net/logopedia/images/8/8f/Netflixicon2016.svg/revision/latest?cb=20170926015226" height="200" />](https://vignette.wikia.nocookie.net/logopedia/images/8/8f/Netflixicon2016.svg/revision/latest?cb=20170926015226)

SVG full: 
[<img src="https://vignette.wikia.nocookie.net/logopedia/images/0/08/Netflix_2015_logo.svg/revision/latest?cb=20160407230047" height="200" />](https://vignette.wikia.nocookie.net/logopedia/images/0/08/Netflix_2015_logo.svg/revision/latest?cb=20160407230047)

**Comment by gilbarbara** [comment]
Added in 6b63f545834a4d869ff11fb6e1405d871a037bf8

Thanks! And sorry for the delay!
