### ISSUE TITLE
Add cssnext logo

### ISSUE THREAD

**Issue by MoOx** [gilbarbara/logos#25]
I didn't see a CONTRIBUTING.md or instruction on how to submit one, so I will leave the manipulation to you.

![cssnext](https://raw.githubusercontent.com/cssnext/cssnext/master/logo/cssnext-256.png)

icon + text https://github.com/cssnext/cssnext/blob/master/logo/cssnext.svg
icon https://github.com/cssnext/cssnext/blob/master/logo/cssnext-icon.svg 
text https://github.com/cssnext/cssnext/blob/master/logo/cssnext-text.svg

**Comment by gilbarbara** [comment]
Thanks!
added @ a6df8c5feb81efde698dc5f200c707c1527dd442
