### ISSUE TITLE
Aura credit card

### ISSUE THREAD

**Issue by helderburato** [gilbarbara/logos#250]
Aura credit card (SVG full):

![aura](https://s3-sa-east-1.amazonaws.com/applanntech-storage/aura.svg)

**Comment by gilbarbara** [comment]
I couldn't even find a website for this card issuer. Is there one?

**Comment by helderburato** [comment]
@gilbarbara this card is an old product of the [cetelem](https://www.cetelem.com.br/home) company.

**Comment by gilbarbara** [comment]
ok, so is dead?
Thanks for your submission but I can't add brands without even a website.
