### ISSUE TITLE
NPM project

### ISSUE THREAD

**Issue by reardestani** [gilbarbara/logos#251]
I think it's good to release the latest version of your icons also on NPM. It helps others to use easy use https://www.jsdelivr.com for icons cdn.

Similar to this website: https://github.com/simple-icons/simple-icons

**Comment by gilbarbara** [comment]
Hey,

There are almost 10Mb of logos in this repo and adding a package with all of them just to use one it's a bad idea.

Thanks for your suggestion.

**Comment by MartinKolarik** [comment]
@gilbarbara the reason @reardestani suggested publishing this as a package is that jsDelivr can serve files from npm packages so you'd then be able to use individual logos from a CDN like this: https://cdn.jsdelivr.net/gh/gilbarbara/logos@2.0/logos/airbrake.svg

That said, jsDelivr can also serve GitHub releases, so publishing to npm is not strictly necessary. You can find all logos here: https://cdn.jsdelivr.net/gh/gilbarbara/logos@2.0/logos/

**Comment by gilbarbara** [comment]
@MartinKolarik Cool. I guess I'll have to bump the version every now and them.

**Comment by reardestani** [comment]
@MartinKolarik yes, Currently I'm using the Github CDN links in my project but jsDelivr recommend usage of NPM.

@gilbarbara hoping you can release it soon or at least release new version in github so we can use the CDN.

By the way, thanks for you work, it's great.

**Comment by gilbarbara** [comment]
@reardestani 
I won't release it as a NPM package. This was never my goal and the possibility of newbies adding all the logos in their project is gruesome.

I'll try to create new releases from time to time.
And I'm setting up a Cloudfront instance to serve the files through a CDN anyway.

**Comment by MartinKolarik** [comment]
@reardestani yeah I know, I'm one of jsDelivr devs 😄 you are good using the GitHub links in this case.

@gilbarbara any specific reason why you want to setup and maintain your own CDN when there already are existing services that do the same? (and better than Cloudfront)

**Comment by gilbarbara** [comment]
@MartinKolarik I'm already hosting the files with S3 so why not?
Also, I need the files URLs before pushing to GitHub.

**Comment by MartinKolarik** [comment]
I see... I didn't notice you were linking to S3 in the readme already.

**Comment by gilbarbara** [comment]
Sorry that me so long to respond. I've published a new release (2017.12) so there's a new link with all current logos: https://cdn.jsdelivr.net/gh/gilbarbara/logos@2017.12/logos/

👍
