### ISSUE TITLE
ReasonML

### ISSUE THREAD

**Issue by jthegedus** [gilbarbara/logos#255]
[Small square png](https://lh3.googleusercontent.com/6IcoGg3sDPibap3wCO7e2w7ms7kRDR7-xQS-LSF16PJJZTW8b_zXsaLI5vJ3mIWE3J7Qmu8=s85)

[png with full name](https://reasonml.github.io/static/reason_300.5d19cfa6.png)

**Comment by gilbarbara** [comment]
Hey,

is there a vector version?

**Comment by jthegedus** [comment]
Not with acceptable quality. I'm happy to take the time to make one and PR it.

**Comment by gilbarbara** [comment]
Added in 6b63f545834a4d869ff11fb6e1405d871a037bf8

Thanks
