### ISSUE TITLE
Add Java logo

### ISSUE THREAD

**Issue by Ivan-Bastidas** [gilbarbara/logos#26]
Hi, I'd like to request to add the Java logo to the list :)

Thanks,

**Comment by Ivan-Bastidas** [comment]
https://upload.wikimedia.org/wikipedia/commons/a/a4/Java_logo_and_wordmark.svg

**Comment by gilbarbara** [comment]
Added 67287ea9e3214975c86bc0a61aaf65aeca8e8372
