### ISSUE TITLE
Trakt.tv

### ISSUE THREAD

**Issue by JourneyOver** [gilbarbara/logos#260]
https://trakt.tv

Png: https://trakt.tv/assets/logos/medium@2x-35e0303a576fce0e7238db97778c04f2.png

**Comment by JourneyOver** [comment]
Why did you re-open this? Trakt released their own SVG vector images which can be grabbed from https://trakt.tv/branding

**Comment by gilbarbara** [comment]
Because I want to add the logo to the collection...
