### ISSUE TITLE
Elixir icon 

### ISSUE THREAD

**Issue by jalbertsr** [gilbarbara/logos#264]
Elixir is a dynamic, functional language designed for building scalable and high concurrency applications. We want our logo! plss

https://elixir-lang.org/

Thanks in advance!

**Comment by gilbarbara** [comment]
I tried to add the logo before and even asked for a vector file in their repo but they denied my request and almost threatened to sue, so I can't add it...
I was playing with it at the time but I hate this trademark proprietary bullshit so I stopped using it.

https://github.com/elixir-lang/elixir/issues/5212
