### ISSUE TITLE
negative radius in soundcloud

### ISSUE THREAD

**Issue by marvinrichter** [gilbarbara/logos#266]
Even though this doesn't change anything visually in this case, a negative value is not valid for radius in the circle element.

https://github.com/gilbarbara/logos/blob/master/logos/soundcloud.svg

**Comment by gilbarbara** [comment]
Setting it to 0 doesn't change anything visually?

**Comment by marvinrichter** [comment]
Nope, 0 doesn't change anything. Even removing the circle altogether doesn't change anything. Or maybe I just can't see it :)

**Comment by gilbarbara** [comment]
fixed in 1136fc212ee227d9359cda2c447955cf8324aa87

Thanks
