### ISSUE TITLE
Vuetify & Nuxt

### ISSUE THREAD

**Issue by newman99** [gilbarbara/logos#267]
Two Javascript libraries used with Vue.js:

[Vuetify](https://vuetifyjs.com/static/doc-images/logo.svg)

[Nuxt](https://www.headwire.com/img/nuxt.svg)

Thanks!

**Comment by gilbarbara** [comment]
Added in 6b63f545834a4d869ff11fb6e1405d871a037bf8

Thanks

**Comment by adarsh4d** [comment]
Update to Nuxt: https://nuxtjs.org/logos/nuxt-square.svg
