### ISSUE TITLE
Spinnaker logo

### ISSUE THREAD

**Issue by davidB** [gilbarbara/logos#269]
https://www.spinnaker.io/assets/images/spinnaker-logo-inline.svg
[![](https://www.spinnaker.io/assets/images/spinnaker-logo-inline.svg)](https://www.spinnaker.io/assets/images/spinnaker-logo-inline.svg)

a deployment tool usable with AWS, Google Cloud Platform, Kubernetes, Mesos, ...

**Comment by gilbarbara** [comment]
Added in 6b63f545834a4d869ff11fb6e1405d871a037bf8

Thanks
