### ISSUE TITLE
NodeOS

### ISSUE THREAD

**Issue by piranna** [gilbarbara/logos#270]
[NodeOS](http://node-os.com/) logo, available at https://github.com/NodeOS/media/blob/master/NodeOS.svg (raw version at https://raw.githubusercontent.com/NodeOS/media/master/NodeOS.svg).

Disclaimer, I'm lead developer of NodeOS, and did the logo myself using Dia and Inkscape cleaning by hand the paths, but I'm not a graphic design expert...

**Comment by gilbarbara** [comment]
Added in 6b63f545834a4d869ff11fb6e1405d871a037bf8

Thanks

**Comment by piranna** [comment]
You are welcome :-)
