### ISSUE TITLE
Why have "PORN" ont the title? | Por que tem "PORN" no título?

### ISSUE THREAD

**Issue by vluzrmos** [gilbarbara/logos#28]

**Comment by emtudo** [comment]
huahuahua.

**Comment by 3runoDesign** [comment]
KKKKK

**Comment by gilbarbara** [comment]
Cause it's fun.
I think it all started with **Food Porn**[[1]](https://en.wikipedia.org/wiki/Food_porn) back in the 90s.
"This looks so good that it is almost pornographic"

**Comment by vluzrmos** [comment]
[en]
I think some websenses could block that page. But anyway...

[pr-br]
Eu acho que alguns websenses podem bloquear essa página. Mas não importa...

**Comment by gilbarbara** [comment]
Firewall blocking isn't a problem!
This is not a product and I don't care about monolithic companies.
