### ISSUE TITLE
PRISM Break logos

### ISSUE THREAD

**Issue by yegortimoshenko** [gilbarbara/logos#285]
Here are PRISM Break's logos, most are in SVG format: https://gitlab.com/prism-break/prism-break/tree/master/source/assets/logos

That includes a few that we hand-traced, and some that we received directly from project creators by email, and some that were just plain hard to find. You might find it useful, sorry this is not a pull request (busy).

**Comment by gilbarbara** [comment]
Thanks. I'll check them!
