### ISSUE TITLE
Request: Signal logo

### ISSUE THREAD

**Issue by lachlanjc** [gilbarbara/logos#286]

**Comment by gilbarbara** [comment]
Which Signal?

**Comment by lachlanjc** [comment]
the encrypted chat app: https://signal.org/

Wikipedia has PNGs: https://en.wikipedia.org/wiki/Signal_(software)#/media/File:Signal_Blue_Icon.png

**Comment by egold555** [comment]
Here is a basic black and white outline of it.

http://web.golde.org/temp/svg/Signal_Blue_Icon.svg

**Comment by gilbarbara** [comment]
Added in a339cabb020a1fc0d9f9df7cf55dd7d5802a55d9
Thanks
