### ISSUE TITLE
KaiOS

### ISSUE THREAD

**Issue by BesrourMS** [gilbarbara/logos#287]
KaiOS is a feature phone os : https://www.kaiostech.com/
Logo : https://www.dropbox.com/sh/2qihtgrzllws8ki/AABgwXUtyzWSW_W9cA7xPeqZa/Visuals%20and%20videos/Logos/KaiOS

**Comment by gilbarbara** [comment]
Added in 8105552754167524dc5dff22c66f4ac8d9de1ca5
Thanks
