### ISSUE TITLE
Update Netlify logos

### ISSUE THREAD

**Issue by verythorough** [gilbarbara/logos#289]
The icon version of the Netlify logo has changed a bit. The new version can be found here: https://www.netlify.com/img/press/logos/logomark.svg

It would also be nice to include the full version of the Netlify logo (found here: https://www.netlify.com/img/press/logos/full-logo-light.svg), in the pattern of Angular, Backbone, Browserify, Netflix, etc.

**Comment by gilbarbara** [comment]
Updated in 8105552754167524dc5dff22c66f4ac8d9de1ca5
