### ISSUE TITLE
Add nest.js logo to the collection

### ISSUE THREAD

**Issue by Thatkookooguy** [gilbarbara/logos#294]
Nest.js is a node.js framework that got a lot of attention and is being implemented at a rapid rate.
As of writing this, nest.js got 9000+ stars.

might be nice to include their logo: https://nestjs.com/logo-small.5d4d1c8f.svg

**Comment by gilbarbara** [comment]
Added in b65a7dc930f6bd4b4fe8040d6961483391305078
Thanks
