### ISSUE TITLE
Add Jupyter Logo

### ISSUE THREAD

**Issue by PPACI** [gilbarbara/logos#312]
Hi.
Thanks for the great work
[Project Jupyter](https://jupyter.org/) is widely knowed in the data science community. It would be great to have it's logo in this repository.
Here is the logo url : https://fr.wikipedia.org/wiki/Fichier:Jupyter_logo.svg

thank you !

**Comment by gilbarbara** [comment]
Added in ef7b94458308d3fb8c12e9047180bfbbbe3f9164
