### ISSUE TITLE
Add Solid logo

### ISSUE THREAD

**Issue by raulrpearson** [gilbarbara/logos#313]
[Solid](https://solid.mit.edu/) is an exciting new project led by Prof. Tim Berners-Lee, inventor of the World Wide Web, taking place at MIT. The project aims to radically change the way Web applications work today, resulting in true data ownership as well as improved privacy.

https://solid.mit.edu/assets/img/solid-logo.svg

**Comment by gilbarbara** [comment]
Added in a339cabb020a1fc0d9f9df7cf55dd7d5802a55d9
Thanks
