### ISSUE TITLE
Add Conan.io Logo

### ISSUE THREAD

**Issue by Tsubashi** [gilbarbara/logos#319]
https://svgshare.com/i/D51

**Comment by gilbarbara** [comment]
"Over Quota"...

**Comment by DamianoMagrini** [comment]
It is not over quota anymore. Still, I've [attached the SVG](https://github.com/gilbarbara/logos/files/3800734/icon.zip) for convenience.

**Comment by gilbarbara** [comment]
Added in febeadf1e00d13280605d6f571cea949713963f8

Thanks
