### ISSUE TITLE
add tags to logos.json

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/logos#32]
```JSON
...
"javascript": {
 "tags": [
    "language",
    "front-end"
  ]
},
"jquery": {
 "tags": [
    "javascript",
    "library",
    "front-end",
    "dom",
    "animation"
  ]
}
...
```

**Comment by gilbarbara** [comment]
I'm thinking of limit of 5 tags per entry.

• libraries
• frameworks
• runtime systems
• micro services
• preprocessors
• tools
• task runners
• code
• cross-browser testing
• deployment
• code integration
• servers
• hardware
• devOps
• front-end
• back-end
• package manager
• linting
• editors
• IDEs
• prototyping

what else?

**Comment by xPetrus** [comment]
CMS?

**Comment by gilbarbara** [comment]
• CMS
• databases
• postprocessors (autoprefixer?)
• methodology (bem?)

**Comment by xPetrus** [comment]
* VCS
