### ISSUE TITLE
browserlist

### ISSUE THREAD

**Issue by bromso** [gilbarbara/logos#323]
https://github.com/browserslist/browserslist/tree/master/img
https://github.com/browserslist/browserslist/blob/master/img/logo.svg

**Comment by gilbarbara** [comment]
It's already available...

**Comment by bromso** [comment]
Hmmm, I can see that it available now. Perhaps I misspelled the name of tech when I used your awesome app? Thank you anyways! Thank you for an awesome app!

**Comment by gilbarbara** [comment]
You're welcome! :)
