### ISSUE TITLE
Add GetYourGuide

### ISSUE THREAD

**Issue by inverse** [gilbarbara/logos#329]
GetYourGuide is a platform for discovering and booking in destination tours and activities. 

SVG Logo: https://drive.google.com/open?id=1KQmhQO-Qqf0BeHUX6emo-c-i9KpeXB_D

**Comment by gilbarbara** [comment]
Cleanup

**Comment by inverse** [comment]
@gilbarbara why was this closed?

**Comment by gilbarbara** [comment]
It's off-topic.

> A collection of SVG logos for developers/DevOps/geeks

**Comment by inverse** [comment]
How's Airbnb in there then?

**Comment by gilbarbara** [comment]
Because of their open-source projects and guides.

Anyway, I've just checked your [organization](https://github.com/getyourguide?type=source) and there are some good contributions.

I'm re-opening this.

**Comment by gilbarbara** [comment]
Added in c122ccfcfdb15d9958a85696ff2460ac3b01f8ca
Thanks

**Comment by inverse** [comment]
Thanks for doing this:pray:
