### ISSUE TITLE
Outdated Google Play icons

### ISSUE THREAD

**Issue by DamianoMagrini** [gilbarbara/logos#330]
The Google Play symbol and logo use the pre-2016 design.
Updated SVGs:

- [symbol](https://upload.wikimedia.org/wikipedia/commons/c/c9/Google_Play_symbol_2016.svg)
- [complete logo](https://upload.wikimedia.org/wikipedia/commons/3/30/Google_Play.svg)

**Comment by gilbarbara** [comment]
Updated in aaf25561c9a8f102bcad7b778b2a681345939ea9
