### ISSUE TITLE
Webflow 

### ISSUE THREAD

**Issue by adarsh4d** [gilbarbara/logos#331]
SVG: https://www.dropbox.com/sh/cvjgac69arm5m6w/AAA14t7frIjmI5QiCQSEOqdGa?dl=0&preview=webflow-logo-blue.svg

All Assets: https://webflow.com/style-guide

URL: https://webflow.com/

**Comment by gilbarbara** [comment]
Added in d108849295d8d92cef1581142d8b012fe34a8e72
