### ISSUE TITLE
Add logstash & filebeat logos

### ISSUE THREAD

**Issue by adrian-amaglio** [gilbarbara/logos#332]
The elasticsearch and kibana logos are in the repo. Maybe you could add beat and logstash ones?
Edit:
Beat logo: https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt4da03cec7fcabcac/5d0cfe4b77f34fd55839b480/logo-beats-64-color.svg
Logstash logo: https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt8d79255492e03260/5d0cfe54561b9b0b537f94e8/logo-logstash-64-color.svg

**Comment by gilbarbara** [comment]
Added in d108849295d8d92cef1581142d8b012fe34a8e72
