### ISSUE TITLE
Add Microsoft Visual Studio.

### ISSUE THREAD

**Issue by krushiraj** [gilbarbara/logos#337]
We have Visual Studio code icon but not Visual Studio.

![visual-studio](https://user-images.githubusercontent.com/19507241/64506057-c4135d00-d2f3-11e9-8fb8-ef8de7717c6e.png)

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="240" height="240"><path fill="#6a1b9a" d="M36,5L17,21.5L7,14l-3,1.25v17.5L7,34l10-7.5L36,43l8-3V8L36,5z M8,20l5,4l-5,4V20z M24,24l10-7v14 L24,24z"/></svg>
```

**Comment by tsdtsdtsd** [comment]
@krushiraj That one is pretty old.

The current vscode logo [can be found here](https://commons.wikimedia.org/wiki/File:Visual_Studio_Code_1.35_icon.svg)

**Comment by krushiraj** [comment]
Actually I found the VS code logo. But, VS code is different from Visual Studio. Both might share some part common in names, but they are different.

**Comment by tsdtsdtsd** [comment]
My bad, apologies 🙏

**Comment by krushiraj** [comment]
No problem 🙂

**Comment by gilbarbara** [comment]
Actually this is the new Visual Studio logo.
![](https://visualstudio.microsoft.com/wp-content/uploads/2019/06/BrandVisualStudioWin2019-3.svg)

**Comment by gilbarbara** [comment]
Added in aaf25561c9a8f102bcad7b778b2a681345939ea9
