### ISSUE TITLE
Add ArxOne brand

### ISSUE THREAD

**Issue by fhayd** [gilbarbara/logos#338]
Add ArxOne brand logo
![Arx burger min](https://user-images.githubusercontent.com/16001248/64687330-91e83380-d48a-11e9-891b-f2b9534eca6d.png)
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" aria-label="arxone" role="img" clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2"><rect height="512" width="512" rx="15%" fill="#fff"/><g fill="#f68c1e" fill-rule="nonzero"><path d="M290.144 257.012c0 18.79-15.273 34.05-34.156 34.05-18.812 0-34.11-15.26-34.11-34.05 0-18.815 15.298-34.052 34.11-34.052 18.883 0 34.156 15.237 34.156 34.052M255.988 403.646c-19.93-.024-38.905-4.019-56.251-11.196l-12.806 30.846c21.28 8.803 44.587 13.704 69.057 13.704 62.561 0 117.649-31.752 150.012-79.995l-42.747.023c-26.822 28.64-64.89 46.618-107.265 46.618M255.988 110.378a146.52 146.52 0 0156.229 11.172l12.805-30.846C303.765 81.901 280.46 77 255.988 77 193.451 77 138.363 108.752 106 156.972h42.747c26.822-28.616 64.89-46.594 107.241-46.594"/></g></svg>`

**URL:** www.arx.one

**Comment by gilbarbara** [comment]
Thanks for your suggestion but I usually don't add regional brands.
