### ISSUE TITLE
Add Sapper (Svelte) Logo

### ISSUE THREAD

**Issue by tolotrasmile** [gilbarbara/logos#339]
**URL:** https://sapper.svelte.dev
**SVG:** https://sapper.svelte.dev/sapper-logo.svg
**Outline SVG:** https://sapper.svelte.dev/sapper-logo-outline.svg

**Comment by gilbarbara** [comment]
Hey
I'll add Svelte in the next batch but this one feels like adding react-dom with the same logo as React.

**Comment by tolotrasmile** [comment]
Thank you
