### ISSUE TITLE
Add Segment

### ISSUE THREAD

**Issue by lambtron** [gilbarbara/logos#34]
[Segment](https://segment.com)

SVG file logos can be found here:
https://www.dropbox.com/sh/1kebdxo9y1llu91/AACE2Vfwtg2b2SJwCrwCoi5ca/Logos?dl=0

Thanks!

**Comment by gilbarbara** [comment]
Added 67287ea9e3214975c86bc0a61aaf65aeca8e8372

**Comment by lambtron** [comment]
Thanks  @gilbarbara! But is it possible to change the logo from the Aztec wheelie thing to this? 

https://www.dropbox.com/work/Marketing/Segment_Press_Kit/Logos?preview=segment-logo-black.svg

That is a legacy logo that we haven't used in a long time :)

Sorry for the miscommunication and inconvenience!
