### ISSUE TITLE
Correct Go logo

### ISSUE THREAD

**Issue by tsdtsdtsd** [gilbarbara/logos#340]
The gopher is not the projects logo, it's the mascot.

The correct and current logo can be found here: 
- [go-logo-blue.svg](https://golang.org/lib/godoc/images/go-logo-blue.svg)
- [zip-package download](https://golang.org/s/logos)

**Comment by gilbarbara** [comment]
Updated in aaf25561c9a8f102bcad7b778b2a681345939ea9
