### ISSUE TITLE
Outdated Visual Studio Code

### ISSUE THREAD

**Issue by dusansimic** [gilbarbara/logos#342]
Visual Studio Code has changed it's icon two times since one You have here.
Here is the lates one: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png
And here is the older one (but newer than the one in this repo): https://library.kissclipart.com/20180919/wyq/kissclipart-visual-studio-code-icon-clipart-visual-studio-code-92e8f8384915ebbd.jpg

**Comment by gilbarbara** [comment]
Updated in aaf25561c9a8f102bcad7b778b2a681345939ea9
