### ISSUE TITLE
Add Nintendo Logo

### ISSUE THREAD

**Issue by Xader726** [gilbarbara/logos#346]
https://upload.wikimedia.org/wikipedia/commons/0/0d/Nintendo.svg

I had 3 different variations to choose:
White on Red: (This one)
Grey: https://upload.wikimedia.org/wikipedia/commons/7/76/Nintendo_gray_logo.svg
and Red: https://upload.wikimedia.org/wikipedia/commons/b/b3/Nintendo_red_logo.svg

**Comment by gilbarbara** [comment]
Hello, 
There are plenty of generic sites with this logo and we don't want to have every logo in the world in our collection.

Thanks
