### ISSUE TITLE
Add PerfReviews logo

### ISSUE THREAD

**Issue by nucliweb** [gilbarbara/logos#353]
Hello Gil 👋🏼

It will a pleasure if you add we [PerfReviews](https://perf.reviews/) logo in your project.

We have the logo in our Brand repo 👉🏼 [PerfReviews-icon-optimized.svg](https://github.com/PerfReviews/Brand/blob/master/PerfReviews-icon-optimized.svg).

Here you can see a preview:

<img width="156" alt="PerfReviews" src="https://user-images.githubusercontent.com/1307927/67144204-72f07480-f274-11e9-9d9c-287079afbf70.png">

Thanks a lot and good job.

**Comment by nucliweb** [comment]
Btw, in the [repo](https://github.com/PerfReviews/Brand), we have the logo with the name.

<img width="950" alt="PerfReviews" src="https://user-images.githubusercontent.com/1307927/67144287-5143bd00-f275-11e9-9ee1-675b9f904362.png">

**Comment by gilbarbara** [comment]
Cleanup
