### ISSUE TITLE
Add Vector logo

### ISSUE THREAD

**Issue by binarylogic** [gilbarbara/logos#358]
[Vector](https://vector.dev) is a popular modern alternative to Logstash (which you already have included). Here are the assets:

* [Full press-kit page](https://vector.dev/press/)
* [Vector Logo SVG](https://vector.dev/press/vector-icon.svg)

Thanks 😄 !

**Comment by gilbarbara** [comment]
Added in febeadf1e00d13280605d6f571cea949713963f8

Thanks
