### ISSUE TITLE
Add Booqable logo

### ISSUE THREAD

**Issue by jeffreyvanderveer** [gilbarbara/logos#362]
Source: https://d4lmxg2kcswpo.cloudfront.net/packs/media/images/logo-small-941d8d75.svg
URL: https://booqable.com/

**Comment by jeffreyvanderveer** [comment]
@gilbarbara Hi Gil, just checking whether there is something else you need from me.

**Comment by gilbarbara** [comment]
Added in c122ccfcfdb15d9958a85696ff2460ac3b01f8ca
Thanks
