### ISSUE TITLE
Add Skaffolder Logo

### ISSUE THREAD

**Issue by lucarducci** [gilbarbara/logos#364]
From [skaffolder.com](https://www.skaffolder.com)

https://skaffolder.com/img/logo/sk-nero.svg
https://skaffolder.com/img/logo/sk-bianco.svg 
https://skaffolder.com/img/logo/skaffolder_logo-nero.svg
https://skaffolder.com/img/logo/skaffolder_logo-bianco.svg

**Comment by gilbarbara** [comment]
Added in c122ccfcfdb15d9958a85696ff2460ac3b01f8ca
Thanks
