### ISSUE TITLE
Add Xing

### ISSUE THREAD

**Issue by alexanderadam** [gilbarbara/logos#368]
* https://www.xing.com/
* https://en.wikipedia.org/wiki/File:Xing_logo.svg

[Usually they're using only the "x"](https://dev.xing.com/logo_rules) but I don't know the proper SVG source for it.

![Xing Logo](https://upload.wikimedia.org/wikipedia/commons/b/b4/Xing_logo.svg)

**Comment by gilbarbara** [comment]
Cleanup

**Comment by alexanderadam** [comment]
Does cleanup mean that you're not going to add it?

**Comment by gilbarbara** [comment]
Yes.
This a curated collection of logos that I find relevant for the community and adding it would open a precedent for job hunting companies.

**Comment by alexanderadam** [comment]
But LinkedIn is basically the same kind of social network and LinkedIn is included as well.
Does that mean that you're gonna remove LinkedIn?

**Comment by gilbarbara** [comment]
They are not the same, as Linkedin is a professional social networking platform used by millions worldwide, not a simple job hunting tool.

I don't mean to belittle Xing at all, just that adding it would open precedence to other similar tools and as I said, this is a curated collection of logos for developers and designers.

I won't remove any logos unless the company or tool has ended their activities.

Is that ok?

**Comment by alexanderadam** [comment]
> They are not the same, as Linkedin is a professional social networking platform used by millions worldwide, not a simple job hunting tool.

Now I understand. We obviously have a misconception here. Xing is a social networking platform as well and not "a simple job hunting tool". Both platforms offer groups, private messages, events, a social stream and of course job stuff, too. The only difference is a regional shift. But don't take my word: read [the Wikipedia article](https://en.wikipedia.org/wiki/XING#Website) or any other trusted source.
Regarding their functionality they are exactly the same. They compete in the exact same domain.
It's like
