### ISSUE TITLE
Add Mastodon

### ISSUE THREAD

**Issue by alexanderadam** [gilbarbara/logos#369]
* https://joinmastodon.org/
* https://commons.wikimedia.org/wiki/File:Mastodon_Logotype_(Simple).svg

![Mastodon Logo](https://upload.wikimedia.org/wikipedia/commons/4/48/Mastodon_Logotype_%28Simple%29.svg)

**Comment by gilbarbara** [comment]
Added in 8a715e715ac0a6c6e9bb71c1160e5517c7da53d0
Thanks
