### ISSUE TITLE
Add Envoy Proxy Logo

### ISSUE THREAD

**Issue by backtrackbaba** [gilbarbara/logos#372]
Hey Gil, Thank you for your for this awesome project!

I wanted to get [Envoy Proxy](https://www.envoyproxy.io/) added to the list. It's a widely used proxy which has a significant userbase. You can find a few users on the homepage itself.

Project: [envoyproxy.io](https://envoyproxy.io)
SVG: https://d33wubrfki0l68.cloudfront.net/77bb2db951dc11d54851e79e0ca09e3a02b276fa/9c0b7/img/envoy-logo.svg

**Comment by gilbarbara** [comment]
Added in c122ccfcfdb15d9958a85696ff2460ac3b01f8ca
Thanks
