### ISSUE TITLE
Add CRM PipeRun Logo

### ISSUE THREAD

**Issue by tonybolzan** [gilbarbara/logos#375]
Website: https://crmpiperun.com
SVG File: https://crmpiperun.com/wp-content/uploads/2019/01/crm-piperun.svg

**Comment by gilbarbara** [comment]
Hey @tonybolzan 

We usually don't add regional tools since a website in portuguese wouldn't mean anything to most users.
Is there an english version?

**Comment by tonybolzan** [comment]
Hi @gilbarbara our are Brazilian software for Brazilian market, one of the largest CRMs in the country, and have clients in Argentina, Paraguay, Mexico, United States and Portugal. Competing directly with pipedrive and others CRM.

**Comment by gilbarbara** [comment]
Ok, but is there an English version?

**Comment by tonybolzan** [comment]
nope
