### ISSUE TITLE
Add Signal Ultramarine Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#376]
[SVG File](https://upload.wikimedia.org/wikipedia/commons/4/41/Signal_ultramarine_icon.svg)

I am aware there is already a [Signal Logo](https://github.com/gilbarbara/logos/blob/master/logos/signal.svg) included in the repository, but the default logo has an Ultramarine color. See [Signal.org](https://signal.org/)

PS Great collection by the way. I love it ❤

**Comment by gilbarbara** [comment]
Updated in ce9679518d9a014f59a6099c2c2089e10ea19410
