### ISSUE TITLE
Add XFCE logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#378]
[SVG file](https://upload.wikimedia.org/wikipedia/commons/a/ab/Xfce_logo-footprint.svg)

See [XFCE Desktop Enviornment](https://upload.wikimedia.org/wikipedia/commons/a/ab/Xfce_logo-footprint.svg) and [xfce.org](xfce.org)

**Comment by gilbarbara** [comment]
This is another logo I don't think it should be here.
Thanks anyway
