### ISSUE TITLE
Add Deepin Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#379]
[SVG file](https://upload.wikimedia.org/wikipedia/commons/f/f5/Deepin_logo.svg)

See [Deepin OS](https://upload.wikimedia.org/wikipedia/commons/f/f5/Deepin_logo.svg) and [deepin.org](deepin.org)

**Comment by gilbarbara** [comment]
Hey @Redxtorm 

This repo is a curated collection of useful and/or beautiful logos.
I don't plan to have every single logo on it and I never heard about this distro before, so I'll pass.
Thanks anyway!
