### ISSUE TITLE
Add Zorin Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#380]
[SVG File](https://upload.wikimedia.org/wikipedia/commons/7/70/Zorin_OS.svg)

See [Zorin OS](https://en.wikipedia.org/wiki/Zorin_OS) and [zorinos.com](zorinos.com)

**Comment by gilbarbara** [comment]
Added in 17261479e64d27613dfd2f71e66eefae38b3d698
Thanks
