### ISSUE TITLE
Add GNU Bash Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#381]
[Bash Icon SVG](https://upload.wikimedia.org/wikipedia/commons/4/4b/Bash_Logo_Colored.svg)

[GNU Bash Logo](https://upload.wikimedia.org/wikipedia/commons/8/82/Gnu-bash-logo.svg) 

See [Bash (UNIX shell)](https://en.m.wikipedia.org/wiki/Bash_(Unix_shell))

**Comment by gilbarbara** [comment]
Updated in 364c22e4ef1c0d6efbb492172403e4ee0647057a

Thanks
