### ISSUE TITLE
Add Blender Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#382]
[Blender Icon SVG](https://commons.wikimedia.org/wiki/File:Blender_logo_no_text.svg)

[Blender Logo SVG](https://commons.wikimedia.org/wiki/File:Logo_Blender.svg)

See [Blender.org](blender.org)

**Comment by gilbarbara** [comment]
Added in 17261479e64d27613dfd2f71e66eefae38b3d698
Thanks
