### ISSUE TITLE
Add Elixir logo

### ISSUE THREAD

**Issue by prodis** [gilbarbara/logos#386]
Elixir is a dynamic, functional language designed for building scalable and maintainable applications.

![elixir_logo](https://user-images.githubusercontent.com/79254/95866555-580dee80-0d68-11eb-8ac8-ba6699c18f9d.png)

https://elixir-lang.org

The zip file contains:
- elixir-icon.svg
- elixir.svg

[elixir_svg.zip](https://github.com/gilbarbara/logos/files/5371578/elixir_svg.zip)

Related to https://github.com/elixir-lang/elixir-lang.github.com/issues/575.

**Comment by gilbarbara** [comment]
Hey @prodis 

I don't think I'll add this logo after all that copyright bullshit.

**Comment by Neophen** [comment]
@gilbarbara hey i know this was a bit of contraversional thing, and if you still don't wanna do it i understand.
But they now have the trademarks policy:
https://elixir-lang.org/trademarks
and icons
https://github.com/elixir-lang/elixir-lang.github.com/tree/main/downloads/logos

Whatever you feel is best for this repo ofcourse, love your work!
