### ISSUE TITLE
Add TYPO3 logo

### ISSUE THREAD

**Issue by alexander-nitsche** [gilbarbara/logos#388]
Hi Gil,

thanks for your wonderful work by providing supervised SVGs to the world and specifically to PlantUML standard lib. The TYPO3 association would like to add the TYPO3 logo to your set. TYPO3 CMS is an Open Source Enterprise Content Management System with a large global community.

### Preview
![typo3-original-wordmark svg](https://user-images.githubusercontent.com/20297232/98235938-d1ad8c80-1f62-11eb-91cc-8b5bd0081a14.png)

### Zipped SVG
[typo3.zip](https://github.com/gilbarbara/logos/files/5494060/typo3.zip)

Greetings
Alex

**Comment by gilbarbara** [comment]
Added in 17261479e64d27613dfd2f71e66eefae38b3d698
Thanks
