### ISSUE TITLE
Add React Spring

### ISSUE THREAD

**Issue by bromso** [gilbarbara/logos#395]
https://www.react-spring.io/

Animation library for React.

**Comment by gilbarbara** [comment]
Is there an SVG logo? (not animated)

**Comment by bromso** [comment]
The animation of the ball inside the spring is the the logo, and it is actually the SVG on the website. :D

For easy access and I've put it in a shared Google Drive folder.

https://drive.google.com/drive/folders/1Xx0QSKmdpmxevEle073iAC6y3sseZbTz?usp=sharing

You said thank you several times to my adds. But there is no need for saying thank you. I am the one that needs to say it! ;)

So thank you! :D

**Comment by gilbarbara** [comment]
@bromso 
Thanks for collaborating! 😄 

I've downloaded the file, you can remove it.

**Comment by bromso** [comment]
Happy to help! :)

**Comment by gilbarbara** [comment]
I'll close it when after it's added

**Comment by bromso** [comment]
Sorry! :)

**Comment by gilbarbara** [comment]
Added in 8a715e715ac0a6c6e9bb71c1160e5517c7da53d0
Thanks
