### ISSUE TITLE
Update LinkedIn logo

### ISSUE THREAD

**Issue by bromso** [gilbarbara/logos#398]
Would be awesome if the current LinkedIn logo could be updated.

And if you could please add like just the 'in' logo so to speak.
Download link from the official LinkedIn brand guideline site: https://content.linkedin.com/content/dam/me/brand/en-us/brand-home/downloads/LinkedIn-Logos.zip

https://brand.linkedin.com/en-us

The 'in' logo I'm refering to: https://content.linkedin.com/content/dam/me/business/en-us/amp/brand-site/v2/bg/LI-Bug.svg.original.svg

Thank in advance!

**Comment by gilbarbara** [comment]
Updated in a02fbe40d0c2e0658ac614783e452fca9d0f17f1
Thanks
