### ISSUE TITLE
Add Commitlint

### ISSUE THREAD

**Issue by bromso** [gilbarbara/logos#399]
https://github.com/conventional-changelog/commitlint/blob/master/docs/assets/icon.svg

Linter for Git messages.

**Comment by gilbarbara** [comment]
hey @bromso 
Not sure about this one.
I've added a few libraries, such as redux, react-router-dom, and react-spring but I don't see why people would use this one.

**Comment by bromso** [comment]
It is a very well known repository. Has a pretty high level of stars & followers.
Is a linter for your Git commits. What eg. ESLint & Prettier is for your code.
But hey, you own this repo, you decide! :) ;)

![image](https://user-images.githubusercontent.com/4441528/109115053-2c076e80-7747-11eb-99e3-2cc8ab4c8fc1.png)
