### ISSUE TITLE
Add Apostrophe CMS

### ISSUE THREAD

**Issue by bromso** [gilbarbara/logos#403]
https://apostrophecms.com/

The logo in the navbar is a SVG.

**Comment by gilbarbara** [comment]
Added in 8a715e715ac0a6c6e9bb71c1160e5517c7da53d0
Thanks

**Comment by bromso** [comment]
@gilbarbara I think you forgot to make the three objects inside the black box so to speak into outlines before you resized it. So it isn't corrent as you can see in the images attached below.

![image](https://user-images.githubusercontent.com/4441528/108082645-fdb8cd80-707a-11eb-9992-2ad67d853b36.png)
![image](https://user-images.githubusercontent.com/4441528/108082674-04dfdb80-707b-11eb-9d29-8e90417d8983.png)

Thank you for a great service non the less! :)

**Comment by gilbarbara** [comment]
Oops! :)

Fixed in 6a4ca0a0f3389cc3e244fcc0599fd3f021a86b07
