### ISSUE TITLE
Add Delicious Logo

### ISSUE THREAD

**Issue by ekryski** [gilbarbara/logos#41]
Delicious is a new database client I'm working on. Would love to see the logo up there! Thanks :smile: 

[Website](http://deliciousdb.com/), [SVG Logo Link](https://github.com/ekryski/delicious-logo/blob/master/delicious-burger.svg)

![Delicious](https://raw.githubusercontent.com/ekryski/delicious-logo/master/delicious-burger.png)

**Comment by gilbarbara** [comment]
Nice logo, thanks!
Added 4b308cb3a171cc0ee09ae3ebcf37688ff5ce28cd

**Comment by ekryski** [comment]
:heart: thanks!
