### ISSUE TITLE
Add wildfly logo

### ISSUE THREAD

**Issue by boukadam** [gilbarbara/logos#410]
Logo with text: https://design.jboss.org/wildfly/logo/final/wildfly_logomark.svg
Logo : https://design.jboss.org/wildfly/logo/final/wildfly_logo.svg

More : https://design.jboss.org/wildfly/index.htm

**Comment by gilbarbara** [comment]
Added in aed2ea95fe65ecb2b32dac2e3384f7fd333587b0
Thanks
