### ISSUE TITLE
Add drools logo

### ISSUE THREAD

**Issue by boukadam** [gilbarbara/logos#419]
https://design.jboss.org/jbossrules/logo/final/drools_logo.svg
https://design.jboss.org/jbossrules/logo/final/drools_icon.svg

https://www.drools.org/

**Comment by gilbarbara** [comment]
Hey @boukadam 

Thanks for your contributions!
But this is a curated collection of logos, so I don't aim to add every single logo. There are already tons of generic vector sites...

That said, I'll add some of these but probably not all of them.

**Comment by boukadam** [comment]
Hi @gilbarbara, can you consider the integration of this logo ?

**Comment by boukadam** [comment]
of all the requests I made this was the most important logo. I hope that one day it will be integrated into this database
