### ISSUE TITLE
Add Postgraphile Logo

### ISSUE THREAD

**Issue by maxkorp** [gilbarbara/logos#423]
https://www.graphile.org/postgraphile/

Link to the svg from the repo: https://cdn.rawgit.com/graphile/graphile.github.io/a6225f8c3052df5c276ecef28aeb0cade1aec16a/logos/postgraphile.optimized.svg

![image](https://user-images.githubusercontent.com/1302526/103574351-fce22880-4e8c-11eb-989f-f9a746cff534.png)

**Comment by gilbarbara** [comment]
Added in aed2ea95fe65ecb2b32dac2e3384f7fd333587b0
Thanks
