### ISSUE TITLE
Add TYPO3 icon

### ISSUE THREAD

**Issue by alexander-nitsche** [gilbarbara/logos#425]
Hi Gil,

along with issue #388 we would like to provide the icon-only variant of the TYPO3 logo as well. Please find it in the below zip file.

### Preview

![typo3-icon](https://user-images.githubusercontent.com/20297232/103638959-ebad2080-4f4d-11eb-9b66-7bef417d64be.png)

### Zipped SVG

[typo3-icon.zip](https://github.com/gilbarbara/logos/files/5769723/typo3-icon.zip)

Thank you and have a nice day
Alex

**Comment by gilbarbara** [comment]
Added in 5c37ced5af141246a5ebbfca4875a2e4f379ab5f
Thanks

**Comment by alexander-nitsche** [comment]
Thank you!
