### ISSUE TITLE
add NumPy logo

### ISSUE THREAD

**Issue by rahulhgdev** [gilbarbara/logos#428]
<img width="501" alt="numpy" src="https://user-images.githubusercontent.com/67586773/105040771-43887300-5a88-11eb-9f01-bee100b9ef22.png">

## svg link
https://commons.wikimedia.org/wiki/File:NumPy_logo_2020.svg

**Comment by gilbarbara** [comment]
Added in aed2ea95fe65ecb2b32dac2e3384f7fd333587b0
Thanks
