### ISSUE TITLE
add Matplotlib logo

### ISSUE THREAD

**Issue by rahulhgdev** [gilbarbara/logos#429]
## png
![matplotlib-tutorial](https://user-images.githubusercontent.com/67586773/105041254-c3164200-5a88-11eb-81af-08efce8b4c99.png)

## svg
![1200px-Matplotlib_icon svg](https://user-images.githubusercontent.com/67586773/105041338-dde8b680-5a88-11eb-8acd-11876430c154.png)

**Comment by gilbarbara** [comment]
Added in e8d77487188e7c7a603f977e1a8cccc120d7be9a
Thanks
