### ISSUE TITLE
add PowerBi logo

### ISSUE THREAD

**Issue by rahulhgdev** [gilbarbara/logos#431]
![power bi](https://user-images.githubusercontent.com/67586773/105042068-cfe76580-5a89-11eb-9a94-52d7f4249275.png)

## svg link
https://commons.wikimedia.org/wiki/File:Power_bi_logo_black.svg

**Comment by gilbarbara** [comment]
hey @rahulhgdev 

Microsoft isn't using this logo anymore.
https://en.wikipedia.org/wiki/Microsoft_Power_BI

**Comment by gilbarbara** [comment]
Added in 028450df5370ab04535e3d1b0f5e343232d94d2d
Thanks
