### ISSUE TITLE
Suggestion: Archive the old logo

### ISSUE THREAD

**Issue by Geeyun-JY3** [gilbarbara/logos#433]
Archive the old logo instead of replaceing them with new logo. Just like [Browser Logos](https://github.com/alrra/browser-logos/#old-browser-logos).

**Comment by gilbarbara** [comment]
Hey @Geeyun-JY3 

Unlike Browser Logos' repo, which is very specific and historical, this is a generic collection of tech logos, and I think keeping the old ones would generate confusion and misinformation.

I'll take this into consideration when I refactor the database used to generate this repo but I don't have time for this right now.

Thanks anyway
