### ISSUE TITLE
gnu:net logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#443]
[PNG Logo](https://gnunet.org/static/images/gnunet-logo-dark-text.png)

[SVG Logo from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/a/a1/Official_logo_of_the_GNUnet_project.svg)

[Website](https://gnunet.org/en/index.html)

[Wikipedia](https://en.m.wikipedia.org/wiki/GNUnet)

**Comment by gilbarbara** [comment]
Added in 88a6c9422eee765ae98c8072f713624051e66aea
Thanks
