### ISSUE TITLE
Tribler Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#444]
[PNG logo from Wikipedia](https://commons.m.wikimedia.org/wiki/File:Tribler_logo.png)

[Website](https://www.tribler.org/)

[Wikipedia](https://en.m.wikipedia.org/wiki/Tribler#)

**Comment by gilbarbara** [comment]
I need an SVG logo

**Comment by gilbarbara** [comment]
Sorry, I can't keep open issues for these cases
