### ISSUE TITLE
OpenJS Foundation Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#445]
[Logo Collection](https://github.com/openjs-foundation/artwork#openjs-foundation-logos)

[Website](https://openjsf.org/)

[Wikipedia](https://en.m.wikipedia.org/wiki/OpenJS_Foundation)

**Comment by gilbarbara** [comment]
Added in e8d77487188e7c7a603f977e1a8cccc120d7be9a
Thanks
