### ISSUE TITLE
Zeronet Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#446]
[SVG logo](https://en.m.wikipedia.org/wiki/File:ZeroNet_vector_logo.svg) 

[Website](https://zeronet.io/) 

[Wikipedia](https://en.m.wikipedia.org/wiki/ZeroNet)

**Comment by gilbarbara** [comment]
The project seems [dead](https://github.com/HelloZeroNet/ZeroNet/issues/2749#issuecomment-872131028)
