### ISSUE TITLE
Processing Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#448]
[PNG Logo](https://github.com/processing/processing/blob/master/build/shared/lib/icons/pde-1024.png)

An SVG logo is currently not available unfortunately. But still, this one looks too pretty. I hope somebody can convert it into SVG format.

[Website](http://processing.org/)

[Wikipedia](https://en.wikipedia.org/wiki/Processing_(programming_language))

**Comment by gilbarbara** [comment]
Sorry, I can't keep open issues for these cases

**Comment by Redxtorm** [comment]
Understandable
