### ISSUE TITLE
Cinder Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#449]
[SVG Logo](https://camo.githubusercontent.com/bc307cb2e7d9bd5ae37a1312b0fa3d472ffecec756496acf368a9dad4bd60d4d/68747470733a2f2f6c696263696e6465722e6f72672f646f63732f5f6173736574732f696d616765732f63696e6465725f6c6f676f2e737667)

[Website](https://libcinder.org/)

[Wikipedia](https://en.wikipedia.org/wiki/Cinder_(programming_library))

**Comment by gilbarbara** [comment]
Added in 028450df5370ab04535e3d1b0f5e343232d94d2d
Thanks
