### ISSUE TITLE
TypeScript-Node Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#453]
[Logo](https://github.com/TypeStrong/ts-node/blob/HEAD/logo.svg?sanitize=true)

[Github Repo](https://github.com/TypeStrong/ts-node)

[NPM page](https://www.npmjs.com/package/ts-node)

**Comment by gilbarbara** [comment]
Added in de8fdaf0ce10dc9f0c41e7f0612da5d2d36f4e74
