### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by chasegiunta** [gilbarbara/logos#455]
[OneDrive Logo SVG](https://upload.wikimedia.org/wikipedia/commons/d/d3/Microsoft_Office_OneDrive_%282018%E2%80%93present%29.svg)

**Comment by paulwaldmann** [comment]
The link is not working, use this one instead.

[Microsoft Office OneDrive (2019–present).svg](https://upload.wikimedia.org/wikipedia/commons/3/3c/Microsoft_Office_OneDrive_%282019%E2%80%93present%29.svg)

**Comment by gilbarbara** [comment]
Added in 028450df5370ab04535e3d1b0f5e343232d94d2d
Thanks
