### ISSUE TITLE
Microsoft Intune & Intune Company Portal

### ISSUE THREAD

**Issue by johngagefaulkner** [gilbarbara/logos#458]
![image](https://user-images.githubusercontent.com/46038619/114792015-825f5980-9d55-11eb-89e7-ece6259b5f9b.png)

[Apple App Store | Intune Company Portal](https://apps.apple.com/us/app/intune-company-portal/id719171358)

**Comment by johngagefaulkner** [comment]
![image](https://user-images.githubusercontent.com/46038619/114791982-6fe52000-9d55-11eb-87ef-10bcf38aed3b.png)

**Comment by johngagefaulkner** [comment]
Were you able to add these?

**Comment by gilbarbara** [comment]
nope
