### ISSUE TITLE
add Kali Linux

### ISSUE THREAD

**Issue by vivian-dai** [gilbarbara/logos#463]
penetration OS that is more beginner friendly than Arch Linux

[Logo download](https://iconape.com/kali-linux-logo-logo-icon-svg-png.html)

[Website](https://www.kali.org/)

**Comment by AndreAugustoAAQ** [comment]
Here is the repository link on GitLab with the official logo files
[Kali Linux Graphic Resources](https://gitlab.com/kalilinux/documentation/graphic-resources)
