### ISSUE TITLE
Add Modoka Logo SVG 

### ISSUE THREAD

**Issue by fxuad** [gilbarbara/logos#465]
Source: https://raw.githubusercontent.com/modoka-studios-entertainment/Modoka/ae100d5f0a1b1be32c95b46be67acc71a2c77c1f/MODOKA.svg?token=AIARYMRENVBWWUUZAFZ52X3AYXZZA

**Comment by gilbarbara** [comment]
Thank you for the indication, but this is off-topic.

> A collection of SVG logos for developers/DevOps/geeks
