### ISSUE TITLE
Microsoft Teams

### ISSUE THREAD

**Issue by aeksco** [gilbarbara/logos#468]
**SVG from Wikipedia:**

```
https://upload.wikimedia.org/wikipedia/commons/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg
```

**PNG preview**

![Microsoft Teams Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg/512px-Microsoft_Office_Teams_%282018%E2%80%93present%29.svg.png)

**Comment by gilbarbara** [comment]
Added in 028450df5370ab04535e3d1b0f5e343232d94d2d
Thanks
