### ISSUE TITLE
Add Cardano Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#472]
[Logo](https://upload.wikimedia.org/wikipedia/commons/f/f8/Cardano.svg)

[Website](https://cardano.org/) 

[Wikipedia Page](https://en.m.wikipedia.org/wiki/Cardano_(blockchain_platform))

**Comment by gilbarbara** [comment]
Added in de8fdaf0ce10dc9f0c41e7f0612da5d2d36f4e74
Thanks
