### ISSUE TITLE
Add Spotify logo

### ISSUE THREAD

**Issue by Nzent** [gilbarbara/logos#474]
need spotify logo
https://1000logos.net/spotify-logo/

![2021-08-28T01_47_58](https://user-images.githubusercontent.com/26079832/131212033-f5ff8f23-5921-4aa2-848a-110dd27e2b42.png)

**Comment by gilbarbara** [comment]
Added in 8479f2f0367b50d7201f2c792d1a925f0c3a2951
Thanks
