### ISSUE TITLE
Add Rocky Linux

### ISSUE THREAD

**Issue by dusansimic** [gilbarbara/logos#477]
Icon: https://github.com/rocky-linux/branding/blob/main/logo/out/icon-bg_transparent-primary-1024x.png
Logo: https://github.com/rocky-linux/branding/blob/main/logo/out/logo-bg_transparent-primary_black-1024x.png

Repo with all resources: https://github.com/rocky-linux/branding

**Comment by gilbarbara** [comment]
Added in 028450df5370ab04535e3d1b0f5e343232d94d2d
Thanks
