### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by xPetrus** [gilbarbara/logos#48]
Awesome - A Curated List of Awesome Lists

https://github.com/sindresorhus/awesome

**Comment by gilbarbara** [comment]
Cool. I had it in my icebox for a while but I wasn't sure if it would fit here, but yeah, it does.
Added 9926b3d01fb9abffa26e95cebaf441285581f224

**Comment by gilbarbara** [comment]
@sindresorhus :+1:

**Comment by xPetrus** [comment]
Awesome!!!

**Comment by sindresorhus** [comment]
:+1:
