### ISSUE TITLE
Add James Webb Space Telescope Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#485]
[Main Logo](https://commons.m.wikimedia.org/wiki/File:James_Webb_Space_Telescope_logo.svg)

[JWST Decal](https://commons.m.wikimedia.org/wiki/File:JWST_decal.svg)

[Website](https://www.jwst.nasa.gov/)

[Wikipedia Page](https://en.m.wikipedia.org/wiki/James_Webb_Space_Telescope)

**Comment by gilbarbara** [comment]
This falls outside the scope of this repo.

**Comment by Redxtorm** [comment]
Okay
