### ISSUE TITLE
Add IBM AIX Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#486]
[Logo](https://en.m.wikipedia.org/wiki/File:IBM_AIX_logo_(2021).svg)

[Wikipedia Page](https://en.m.wikipedia.org/wiki/IBM_AIX)

[Website](https://www.ibm.com/it-infrastructure/power/os/aix)

**Comment by gilbarbara** [comment]
Added in 9ef3264351d651401a679e2041980dff3ae7b128
Thanks
