### ISSUE TITLE
Pardus OS Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#488]
[Logo](https://en.m.wikipedia.org/wiki/File:Pardus-tescil_Linux_logo.svg)

[Wikipedia Page](https://en.m.wikipedia.org/wiki/Pardus_(operating_system))

[Website](https://www.pardus.org.tr/)

**Comment by gilbarbara** [comment]
No regional software allowed

As I said in the issue template: 
>  This is a curated collection of logos and I don't aim to add every single logo

Also, please slow down with the requests?
I'm trying to clean up the queue and you are flooding it...

**Comment by Redxtorm** [comment]
Ohh I'm sorry 😅
