### ISSUE TITLE
Shopify Logo

### ISSUE THREAD

**Issue by cheapwebmonkey** [gilbarbara/logos#49]
Please add Shopify logo

https://github.com/cheapwebmonkey/logos/blob/master/shopify-default.svg

**Comment by gilbarbara** [comment]
This link is an image encapsulated in a svg, not a true vector.
Anyway, in this first phase I'm just adding developer tools and service (and the ocasional gorgeous logo) but I'm thinking about rewriting the front-end soon and splitting into categories. Shopify is already in my icebox.
Thanks
