### ISSUE TITLE
Add httpie

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#494]
[httpie.io](https://httpie.io/)

[Logo](https://raw.githubusercontent.com/httpie/httpie/master/docs/httpie-logo.svg)

[Github Repo](https://github.com/httpie/httpie)

HTTPie (pronounced aitch-tee-tee-pie) is a command-line HTTP client. Its goal is to make CLI interaction with web services as human-friendly as possible. HTTPie is designed for testing, debugging, and generally interacting with APIs & HTTP servers. The http & https commands allow for creating and sending arbitrary HTTP requests. They use simple and natural syntax and provide formatted and colorized output.

**Comment by gilbarbara** [comment]
Added in 101422a2467fd45d5ba0f1da6f199c84236d0ec3
Thanks
