### ISSUE TITLE
Add SpiderMonkey

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#495]
[spidermonkey.dev](https://spidermonkey.dev/)

**SpiderMonkey** is Mozilla’s JavaScript and WebAssembly Engine, used in Firefox, Servo and various other projects. It is written in C++, Rust and JavaScript. You can embed it into C++ and Rust projects, and it can be run as a stand-alone shell.

[Logo](https://en.m.wikipedia.org/wiki/File:Spidermonkey-logo-2021.svg)

[Wikipedia Page](https://en.m.wikipedia.org/wiki/SpiderMonkey)

**Comment by gilbarbara** [comment]
Added in 101422a2467fd45d5ba0f1da6f199c84236d0ec3
Thanks
