### ISSUE TITLE
Add TOML

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#496]
[Toml.io](https://toml.io/en/)

[Wikipedia Page](https://en.m.wikipedia.org/wiki/TOML)

[Github Page](https://github.com/toml-lang/toml) 

**TOML** is a file format for configuration files. It is intended to be easy to read and write due to obvious semantics which aim to be "minimal", and is designed to map unambiguously to a dictionary.

[Logo](https://en.m.wikipedia.org/wiki/File:TOML_Logo.svg)

Please note that this logo is slightly different from the one seen on [toml.io](https://toml.io/en/). The logo on official website has red brackets instead of grey. Unfortunately the [toml.io](https://toml.io/en/) version is not a self contained SVG file.

**Comment by gilbarbara** [comment]
Added in 101422a2467fd45d5ba0f1da6f199c84236d0ec3
Thanks
