### ISSUE TITLE
Add Deno New Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#497]
[Logo from deno.land](https://deno.land/logo.svg)

[Logo from Wikimedia Commons](https://commons.m.wikimedia.org/wiki/File:Deno_2021.svg)

[deno.land](https://deno.land/)

[Github Repo](https://github.com/denoland/deno)

**Comment by gilbarbara** [comment]
Updated in 65e74211994702998f96083a6ac027fe1cb2e28d
Thanks
