### ISSUE TITLE
Add Micro

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#499]
[micro-editor.github.io](https://micro-editor.github.io/)

[Github repo](https://github.com/zyedidia/micro) 

micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the capabilities of modern terminals.

[Logo](https://github.com/zyedidia/micro/blob/master/assets/micro-logo.svg)

**Comment by gilbarbara** [comment]
Added in 3f8b2dd45dac2ecde1cd40cc4146369226fe7507
Thanks
