### ISSUE TITLE
Add Reactor logo

### ISSUE THREAD

**Issue by andreshincapier** [gilbarbara/logos#501]
[Official repo PNG](https://github.com/reactor/reactor-core/blob/main/docs/asciidoc/images/logo.png), or [Unofficial PNG and SVG](https://github.com/andreshincapier/reactor-logo).

[Project reactor](https://projectreactor.io/).

[Github Repo](https://github.com/reactor).

Reactive Streams based projects for backpressure-ready asynchronous message passing.

**Comment by gilbarbara** [comment]
hey @andreshincapier 
The SVG you posted isn't a vector file and we can't use that...
If you find a proper vector file, you can reopen this issue.
