### ISSUE TITLE
Add BrainJS

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#502]
[brain.js.org](https://brain.js.org/#/)

Brain.js is a GPU accelerated library for Neural Networks written in JavaScript for Browsers and NodeJS.

[Github repo](https://github.com/BrainJS/brain.js)

[Logo](https://brain.js.org/img/logo.svg)

**Comment by gilbarbara** [comment]
Added in 8377b0c46390a1cb24005369469418340e3fe3e9
Thanks
