### ISSUE TITLE
Add Neo4j new logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#503]
[neo4j.com](https://neo4j.com/)

Neo4j is a graph database management system developed by Neo4j, Inc.

[Wikipedia Page](https://en.m.wikipedia.org/wiki/Neo4j)

[Logo](https://dist.neo4j.com/wp-content/uploads/20210423072428/neo4j-logo-2020-1.svg)

**Comment by gilbarbara** [comment]
Updated in a8dee6d53c329dac2399aea1986a646f17837a06
