### ISSUE TITLE
Add GnuPG Logo

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#504]
[gnupg.org](https://gnupg.org/)
 
GnuPG is a complete and free implementation of the OpenPGP standard as defined by RFC4880 (also known as PGP). GnuPG allows you to encrypt and sign your data and communications; it features a versatile key management system, along with access modules for all kinds of public key directories. GnuPG, also known as GPG, is a command line tool with features for easy integration with other applications.

[Wikipedia Page](https://en.m.wikipedia.org/wiki/GNU_Privacy_Guard)

[Logo](https://en.m.wikipedia.org/wiki/File:Gnupg_logo.svg)

**Comment by gilbarbara** [comment]
Added in f31ecd8b034658fd5b1dd40aa16614767aeaa9ee
Thanks
