### ISSUE TITLE
Add `vitest` logo

### ISSUE THREAD

**Issue by userquin** [gilbarbara/logos#506]
**Name with link**
vitest: https://github.com/vitest-dev/vitest

**Description**
A blazing fast unit test framework powered by Vite. 

**Link to the vector file, preferably from an official source**
https://github.com/vitest-dev/vitest/blob/main/docs/public/logo.svg

**Comment by gilbarbara** [comment]
Added in de8fdaf0ce10dc9f0c41e7f0612da5d2d36f4e74
Thanks
