### ISSUE TITLE
Add `vueuse` logo

### ISSUE THREAD

**Issue by userquin** [gilbarbara/logos#507]
**Name with link**
vueuse: https://github.com/vueuse/vueuse/

**Description**
Collection of essential Vue Composition Utilities

**Link to the vector file, preferably from an official source**
Should remove extra space:
https://github.com/vueuse/vueuse/blob/main/packages/public/favicon.svg

**Comment by gilbarbara** [comment]
Added in de8fdaf0ce10dc9f0c41e7f0612da5d2d36f4e74
Thanks
