### ISSUE TITLE
Add `UnoCSS` logo

### ISSUE THREAD

**Issue by userquin** [gilbarbara/logos#508]
Add `UnoCSS` logo

**Name with link**
unocss: https://github.com/unocss/unocss/

**Description**
The instant on-demand Atomic CSS engine.

**Link to the vector file, preferably from an official source**
https://github.com/unocss/unocss/blob/main/playground/public/icon.svg

**Comment by gilbarbara** [comment]
Added in de8fdaf0ce10dc9f0c41e7f0612da5d2d36f4e74
Thanks
