### ISSUE TITLE
Add Bootstrap Vue

### ISSUE THREAD

**Issue by CelsonF** [gilbarbara/logos#509]
**BOOTSTRAP VUE**
*[Bootstrap Vue](https://bootstrap-vue.org/)*

**Description**
With more than 85 components, over 45 available plugins, several directives, and 1000+ icons, BootstrapVue provides one of the most comprehensive implementations of the Bootstrap v4.5 component and grid system available for Vue.js v2.6, complete with extensive and automated WAI-ARIA accessibility markup.

**Link to the vector file, preferably from an official source**
*[Bootstrap Vue](https://github.com/bootstrap-vue/bootstrap-vue)*.

**Alternative**
![bootstrapvue](https://user-images.githubusercontent.com/29209254/152627426-ed1c3a87-49f4-4e0f-98ea-15ce19f083ac.svg)

**Comment by gilbarbara** [comment]
Hey @CelsonF 

Thanks for your contribution but I don't add derivative icons (React Bootstrap, Vue Bootstrap, etc)
👍🏻
