### ISSUE TITLE
Where's the legendary editors

### ISSUE THREAD

**Issue by tallesl** [gilbarbara/logos#51]
[Vim][vim] and [Emacs][emacs]?

[vim]:      https://commons.wikimedia.org/wiki/File:Vimlogo.svg
[emacs]: https://commons.wikimedia.org/wiki/File:Emacs-logo.svg

**Comment by gilbarbara** [comment]
In the past, their logos are fugly! :grin:

**Comment by tallesl** [comment]
Hey, folks still love it ([so much that they are even up to rewrite it][neovim]).

And if this is a *beauty contest*  I don't know how [json][json] and [forever][forever] managed to make it.

[neovim]: http://neovim.io
[json]:      https://github.com/gilbarbara/logos/blob/master/logos/json.svg
[forever]: https://github.com/gilbarbara/logos/blob/master/logos/forever.svg

**Comment by gilbarbara** [comment]
well, this is SVG Porn.
And beauty is in the eye of the beholder.

**Comment by gilbarbara** [comment]
Added vim 88cd084aad8c474cdeeafea75d172ea75369b62c
