### ISSUE TITLE
Add Thymeleaf

### ISSUE THREAD

**Issue by Potherca** [gilbarbara/logos#510]
**Name with link**
Thymeleaf - https://www.thymeleaf.org/

**Description**
Thymeleaf is a popular Java template engine.

They are approaching 5k GitHbub stars.

https://github.com/thymeleaf/ ![](https://img.shields.io/github/stars/thymeleaf?style=social)

**Link to the vector file, preferably from an official source**
I could not find an SVG, only a PNG

<img src="https://www.thymeleaf.org/images/thymeleaf.png" width="100" />

But I have requested one: https://github.com/thymeleaf/thymeleaf.github.com/issues/41

 - - -
_originally logo request: https://github.com/plantuml/plantuml-stdlib/issues/41_

**Comment by gilbarbara** [comment]
hey @Potherca 

Couldn't find a vector too...

**Comment by Potherca** [comment]
Found one! https://github.com/thymeleaf/thymeleaf-org/blob/main/artwork/thymeleaf%202016/thymeleaf.svg
(Thanks to @danielfernandez for pointing it out)

![](https://raw.githubusercontent.com/thymeleaf/thymeleaf-org/main/artwork/thymeleaf%202016/thymeleaf.svg)

@gilbarbara Could this issue be reopened?

**Comment by danielfernandez** [comment]
Please note those vectors need the "Ubuntu" font to be correctly displayed, as stated in: https://github.com/thymeleaf/thymeleaf-org/blob/main/artwork/thymeleaf%202016/THYMELEAF_LOGO_USAGE_AND_SPEC.txt#L28

**Comment by gilbarbara** [comment]
An SVG logo that requires a specific font? That's bonkers...

**Comment by gilbarbara** [comment]
Added in e6c61d4e86536e2ffa2834689a9f44e1d38019e0
Thanks
