### ISSUE TITLE
Helm, DBT, & Argo

### ISSUE THREAD

**Issue by patrickdeutsch-wk** [gilbarbara/logos#511]
Helm Logo 
https://cncf-branding.netlify.app/projects/helm/

Argo Logo
https://cncf-branding.netlify.app/projects/argo/

DBT 
https://www.getdbt.com/brand-guidelines/

Hello, I appreciate your contributions to the space.  I use plantuml to build out diagrams & seem to be lacking on sourcing some commonly used logos in the world of data engineering.  I request to add these 3 brand logs to help update the plantuml library for use in diagrams https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites

**Link to the vector file, preferably from an official source**

**Comment by gilbarbara** [comment]
Added in 101422a2467fd45d5ba0f1da6f199c84236d0ec3
Thanks
