### ISSUE TITLE
Add Framer

### ISSUE THREAD

**Issue by bromso** [gilbarbara/logos#512]
Name: **Framer**
URL: **https://framer.com/**

Description: **Design, Animation & Prototyping software**

Logo: **Can be found on their website**

![Framer Login-0](https://user-images.githubusercontent.com/4441528/153706471-9de7e4c8-3b56-41d3-83dd-7b9adb32c776.svg)

**Comment by gilbarbara** [comment]
Added in 101422a2467fd45d5ba0f1da6f199c84236d0ec3
Thanks
