### ISSUE TITLE
Add Gumroad

### ISSUE THREAD

**Issue by zavbala** [gilbarbara/logos#513]
**Name with link**
Gumroad - https://gumroad.com/

**Description**

Platform to sell digital products

**Link to the vector file, preferably from an official source**

https://assets-global.website-files.com/6171b265e5c8aa59b42c3472/618f28a89e94524552a002cb_g-icon.svg

**Comment by gilbarbara** [comment]
This is out of the scope of this collection.
Thanks anyway!
