### ISSUE TITLE
Add Dgraph

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#517]
[dgraph.io](https://dgraph.io/)

Native GraphQL Database with graph backend

[Github Repo](https://github.com/dgraph-io/dgraph)

[Dgraph Database in 100 seconds by Fireship
](https://youtu.be/OzDG68VvPxY)

[Logo](https://en.m.wikipedia.org/wiki/File:Dgraph-logo.svg)

**Comment by gilbarbara** [comment]
Added in 80c549990a0f513dcbaf3c9eab6a1a620df76088
Thanks
