### ISSUE TITLE
Add React Query

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#518]
[React Query](https://react-query.tanstack.com/)

Fetch, cache and update data in your React and React Native applications all without touching any "global state".

[Github Repo](https://github.com/tannerlinsley/react-query)

[React Query in 100 Seconds by Fireship](https://youtu.be/novnyCaa7To)

[Logo](https://react-query.tanstack.com/_next/static/images/logo-7a7896631260eebffcb031765854375b.svg)

**Comment by gilbarbara** [comment]
Added in 80c549990a0f513dcbaf3c9eab6a1a620df76088
Thanks
