### ISSUE TITLE
Add Naive UI

### ISSUE THREAD

**Issue by Sepush** [gilbarbara/logos#520]
**Name with link**

[Naive UI](https://www.naiveui.com/)

**Description**

A Vue 3 Component Library. Fairly Complete. Customizable Themes. Uses TypeScript. Not too Slow.

**Link to the vector file, preferably from an official source**

[Github](https://github.com/TuSimple/naive-ui)

[Logo](https://github.com/TuSimple/naive-ui/blob/main/demo/assets/images/naivelogo.svg)

**Comment by gilbarbara** [comment]
Added in 80c549990a0f513dcbaf3c9eab6a1a620df76088
Thanks
