### ISSUE TITLE
Add Unreal Engine

### ISSUE THREAD

**Issue by luciewendlandt** [gilbarbara/logos#522]
Name with link:
[Unreal Engine](https://www.unrealengine.com/)

Description:
The world's most advanced real-time 3D creation tool for photoreal visuals and immersive experiences.

Link to the vector file, preferably from an official source:
[Icon](https://de.wikipedia.org/wiki/Unreal_Engine#/media/Datei:UE_Logo_Black_Centered.svg)

This would be useful to find the logo for game developers.
Thank you!

**Comment by gilbarbara** [comment]
Added in 80c549990a0f513dcbaf3c9eab6a1a620df76088
Thanks
