### ISSUE TITLE
Add Godot

### ISSUE THREAD

**Issue by luciewendlandt** [gilbarbara/logos#523]
Name with link:
[Godot](https://godotengine.org/)

Description:
Godot is a game engine. Completely free and open-source under the very permissive MIT license.

Link to the vector file, preferably from an official source:
[Icon](https://commons.wikimedia.org/wiki/File:Godot_icon.svg)

This would be useful to find the logo for game developers.
Thank you!

**Comment by gilbarbara** [comment]
Added in e6c61d4e86536e2ffa2834689a9f44e1d38019e0
Thanks
