### ISSUE TITLE
Update Kotlin logo

### ISSUE THREAD

**Issue by mahozad** [gilbarbara/logos#526]
**Name with link**
[Logo of Kotlin programming language](https://kotlinlang.org/docs/kotlin-logo.html)

**Description**
Kotlin logo and branding has been updated recently.
Could you please update the logo to its latest version?

**Link to the vector file, preferably from an official source**
You can download the logo from [the official website](https://kotlinlang.org/docs/kotlin-logo.html).

Here is a copy:

![Kotlin Full Color Logo Mark RGB](https://user-images.githubusercontent.com/29678011/162138750-b39ad00b-0190-47c2-b0a9-a9a0adf6607a.svg)

**Comment by gilbarbara** [comment]
Updated in a8dee6d53c329dac2399aea1986a646f17837a06
Thanks

**Comment by mahozad** [comment]
Ok. Thank you.
