### ISSUE TITLE
Add Partytown

### ISSUE THREAD

**Issue by dennisfrijlink** [gilbarbara/logos#527]
**Name with link**
[Partytown](https://partytown.builder.io/)
repo: https://github.com/BuilderIO/partytown

**Description**
Partytown is a lazy-loaded library to help relocate resource intensive scripts into a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), and off of the [main thread](https://developer.mozilla.org/en-US/docs/Glossary/Main_thread). Its goal is to help speed up sites by dedicating the main thread to your code, and offloading third-party scripts to a web worker.

**Link to the vector file, preferably from an official source**
Icon: https://raw.githubusercontent.com/BuilderIO/partytown/main/docs/site/public/partytown-logo.svg

Logo:
https://raw.githubusercontent.com/BuilderIO/partytown/main/docs/site/public/partytown.svg

**Comment by gilbarbara** [comment]
Added in 80c549990a0f513dcbaf3c9eab6a1a620df76088
Thanks
