### ISSUE TITLE
Add PyPI

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#528]
[pypi.org](https://pypi.org/) 

The Python Package Index (PyPI) is a repository of software for the Python programming language.

PyPI helps you find and install software developed and shared by the Python community.

Package authors use PyPI to distribute their software.

[Logo](https://pypi.org/static/images/logo-small.95de8436.svg)

**Comment by gilbarbara** [comment]
Added in e6c61d4e86536e2ffa2834689a9f44e1d38019e0
Thanks
