### ISSUE TITLE
Add Conda

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#529]
[conda.io](https://conda.io/)

Package, dependency and environment management for any language—Python, R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, FORTRAN, and more.

Conda is an open source package management system and environment management system that runs on Windows, macOS and Linux. Conda quickly installs, runs and updates packages and their dependencies. Conda easily creates, saves, loads and switches between environments on your local computer. It was created for Python programs, but it can package and distribute software for any language.

[Logo](https://docs.conda.io/en/latest/_images/conda_logo.svg)

**Comment by gilbarbara** [comment]
Added in 1f9332a66b7684f677cc29f1f59f5966f06742ff
Thanks
