### ISSUE TITLE
GGV Logo

### ISSUE THREAD

**Issue by grayghostvisuals** [gilbarbara/logos#53]
Gray Ghost Visuals Press. Animation script rotating the globe can also be included inside the single SVG file. Demo here [http://codepen.io/grayghostvisuals/pen/YXyVXX](http://codepen.io/grayghostvisuals/pen/YXyVXX)

![screen shot 2015-07-08 at 3 19 09 pm](https://cloud.githubusercontent.com/assets/934322/8579805/b996eb4c-2584-11e5-9553-293cff900d0d.png)

**Comment by gilbarbara** [comment]
Hey!
Thanks for your suggestion but I'm not adding studios yet, maybe in a future version.
:+1:
