### ISSUE TITLE
Add Fortran

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#530]
[fortran-lang.org](https://fortran-lang.org/) 

Fortran is a general-purpose, compiled imperative programming language that is especially suited to numeric computation and scientific computing.

[Logo](https://github.com/fortran-lang/fortran-lang.org/blob/master/assets/img/fortran-logo.svg)

**Comment by gilbarbara** [comment]
Added in 8377b0c46390a1cb24005369469418340e3fe3e9
Thanks
