### ISSUE TITLE
Add R Lang

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#531]
[www.r-project.org](https://www.r-project.org/) 

R is a programming language for statistical computing and graphics supported by the R Core Team and the R Foundation for Statistical Computing. R is used among data miners and statisticians for data analysis and developing statistical software.

[Logo](https://www.r-project.org/logo/Rlogo.svg)

**Comment by gilbarbara** [comment]
R is already available. I've changed the name to `R (Language)` to be easier to find
