### ISSUE TITLE
Add Netwide Assembler

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#532]
[NASM](https://nasm.us/)

The Netwide Assembler (NASM) is an assembler and disassembler for the Intel x86 architecture. It can be used to write 16-bit, 32-bit (IA-32) and 64-bit (x86-64) programs. It is considered one of the most popular assemblers for Linux.

[Wikipedia Article](https://en.m.wikipedia.org/wiki/Netwide_Assembler) 

[Logo](https://www.nasm.us/images/svg/nasm_on_white.svg)

**Comment by gilbarbara** [comment]
Added in 9ef3264351d651401a679e2041980dff3ae7b128
Thanks
