### ISSUE TITLE
Add ARM

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#533]
[Arm Ltd.](https://www.arm.com/) 

Arm Ltd. (stylized as arm) is a British semiconductor and software design company based in Cambridge, England. Its primary business is in the design of ARM processors (CPUs).

ARM systems include mostly embedded systems, including all types of phones. Systems, like iPhone and Android smartphones, frequently include many chips, from many different providers, that include one or more licensed Arm cores, in addition to those in the main Arm-based processor. Arm's core designs are also used in chips that support all the most common network-related technologies.

[Logo](https://upload.wikimedia.org/wikipedia/commons/7/77/Arm_logo_2017.svg)

More Information:
[ARM architecture family](https://en.m.wikipedia.org/wiki/ARM_architecture_family)

**Comment by gilbarbara** [comment]
Added in 11f54bac1b6dfad2cbd1c6da9f2245ec8b5ea22b
Thanks
