### ISSUE TITLE
Add SvelteKit

### ISSUE THREAD

**Issue by mojoaxel** [gilbarbara/logos#534]
**Name with link**

[SvelteKit](https://kit.svelte.dev/)

**Description**

See original commit:
https://github.com/mcmxcdev/pnpm.github.io/blob/db169eba20b23a10cedea889e0c87d6b77ddc978/static/img/users/sveltekit.svg

**Link to the vector file, preferably from an official source**

![](https://raw.githubusercontent.com/mcmxcdev/pnpm.github.io/db169eba20b23a10cedea889e0c87d6b77ddc978/static/img/users/sveltekit.svg)

https://raw.githubusercontent.com/mcmxcdev/pnpm.github.io/db169eba20b23a10cedea889e0c87d6b77ddc978/static/img/users/sveltekit.svg

**Comment by gilbarbara** [comment]
Added in f17b380deb6885848536a57763e98de27621cdbe
Thanks
