### ISSUE TITLE
Add LanguageTool

### ISSUE THREAD

**Issue by shadow81627** [gilbarbara/logos#535]
**Name with link**
LanguageTool https://languagetool.org/

**Description**
LanguageTool is a free online proofreading service for English, Spanish, and 20 other languages. Instantly check your text for grammar and style mistakes.

I'm using the icons on my personal website, here https://daim.dev/tools

**Link to the vector file, preferably from an official source**
https://languagetool.org/images/logo_color_with_background.svg?8dae54218b449e94603195c91016bc93

**Comment by gilbarbara** [comment]
Added in f31ecd8b034658fd5b1dd40aa16614767aeaa9ee
Thanks
