### ISSUE TITLE
Add PyScript

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#537]
**Name with link**

[PyScript](https://pyscript.net/)

[Github Repo](https://github.com/pyscript/pyscript) 

**Description**

PyScript is a framework that allows users to create rich Python applications in the browser using HTML’s interface. PyScript aims to give users a first-class programming language that has consistent styling rules, is more expressive, and is easier to learn.

**Link to the vector file, preferably from an official source**

[Logo](https://pyscript.net/assets/images/pyscript-sticker-black.svg)

**Comment by gilbarbara** [comment]
Added in 9ef3264351d651401a679e2041980dff3ae7b128
Thanks
