### ISSUE TITLE
Add FFmpeg

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#538]
**Name with link**
FFmpeg
https://ffmpeg.org/

**Description**

A complete, cross-platform solution to record, convert and stream audio and video.

**FFmpeg** is a free and open-source software project consisting of a suite of libraries and programs for handling video, audio, and other multimedia files and streams. At its core is the command-line `ffmpeg` tool itself, designed for processing of video and audio files. It is widely used for format transcoding, basic editing (trimming and concatenation), video scaling, video post-production effects and standards compliance (SMPTE, ITU).

**Link to the vector file, preferably from an official source**

> [Current Logo](https://en.m.wikipedia.org/wiki/File:FFmpeg_Logo_new.svg)

> [Older Flat Logo](https://commons.m.wikimedia.org/wiki/File:FFmpeg-Logo.svg)

**More Links**

> [FFmpeg (Wikipedia)](https://en.m.wikipedia.org/wiki/FFmpeg) 

> [Github Mirror](https://github.com/FFmpeg/FFmpeg)

**Comment by gilbarbara** [comment]
Added in e6c61d4e86536e2ffa2834689a9f44e1d38019e0
Thanks
