### ISSUE TITLE
Add Kdenlive

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#539]
**Name with link**
Kdenlive
https://kdenlive.org/en/

**Description**

Kdenlive (acronym for KDE Non-Linear Video Editor) is a free and open-source video editing software based on the MLT Framework, KDE and Qt. The project was started by Jason Wood in 2002, and is now maintained by a small team of developers.

**Link to the vector file, preferably from an official source**

> [Logo Collection](https://kdenlive.org/wp-content/uploads/2017/01/kdenlive-logo-manual.svg)

**More Links**

> [Kdenlive (Wikipedia)](https://en.m.wikipedia.org/wiki/Kdenlive)

**Comment by gilbarbara** [comment]
Apps are out of scope save some rare exceptions
