### ISSUE TITLE
open source hardware logo

### ISSUE THREAD

**Issue by syxanash** [gilbarbara/logos#54]
![open source hardware](http://www.oshwa.org/wp-content/uploads/2014/03/oshw-logo-200-px.png)

I've noticed [Arduino](https://camo.githubusercontent.com/2d760bc87f38ec76931ede7297e13760e1da0e87/687474703a2f2f67696c626172626172612e6769746875622e696f2f6c6f676f732f61726475696e6f2e737667) logo in your repository so I would suggest to add [Open Source Hardware](http://www.oshwa.org/) logo too.

here is the link to svg file:
http://www.oshwa.org/wp-content/uploads/2014/03/oshw-logo.svg

**Comment by gilbarbara** [comment]
Added 88cd084aad8c474cdeeafea75d172ea75369b62c
