### ISSUE TITLE
Add Streamlit

### ISSUE THREAD

**Issue by MaximilianFreitag** [gilbarbara/logos#540]
**Name with link**
[Streamlit github repo](https://github.com/streamlit/streamlit)

**Description**
Streamlit is an open-source python framework for building web apps for Machine Learning and Data Science

**Link to the vector file, preferably from an official source**
https://streamlit.io/images/brand/streamlit-logo-primary-colormark-darktext.svg

**Comment by gilbarbara** [comment]
Added in e6c61d4e86536e2ffa2834689a9f44e1d38019e0
Thanks
