### ISSUE TITLE
Add WalkMe

### ISSUE THREAD

**Issue by shrikster** [gilbarbara/logos#541]
**Name with link**
WalkMe

https://www.walkme.com

**Description**
WalkMe is an American multinational software-as-a-service (SaaS) company, with headquarters in San Francisco, California .Its Digital Adoption Platform (DAP) was recognized in Everest Group's PEAK Matrix Assessment of DAP vendors as the leading DAP product. Alongside its headquarters in San Francisco, the company has offices in Raleigh North Carolina , Tel Aviv  Israel, and a global footprint including the United Kingdom, Australia, and Japan.

WalkMe has more than 2,000 corporate customers and has been recognized on the Forbes Cloud 100 for five consecutive years.As of December 2019, WalkMe has raised more than US$307 million in venture capital funding and is valued at US$2 billion, making it a unicorn company.
The company's [initial public offering](https://en.wikipedia.org/wiki/Initial_public_offering) (IPO) took place on June 16, 2021, and resulted in a valuation of US$2.56 billion.

**Link to the vector file, preferably from an official source**
https://www.walkme.com/wp-content/uploads/2022/01/walkme-logo.svg

https://www.walkme.com/brand-resources/

**Comment by gilbarbara** [comment]
Added in 1f372be75689d73cae89b6de808149b606b879e1
Thanks
