### ISSUE TITLE
Add MicroPython

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#542]
**Name with link**
MicroPython
https://micropython.org/

**Description**
MicroPython is a lean and efficient implementation of the [Python 3](http://www.python.org/) programming language that includes a small subset of the Python standard library and is optimised to run on microcontrollers and in constrained environments.

 MicroPython is packed full of advanced features such as an interactive prompt, arbitrary precision integers, closures, list comprehension, generators, exception handling and more. Yet it is compact enough to fit and run within just 256k of code space and 16k of RAM.

MicroPython aims to be as compatible with normal Python as possible to allow you to transfer code with ease from the desktop to a microcontroller or embedded system. 

**Link to the vector file, preferably from an official source**

> [Logo](https://en.m.wikipedia.org/wiki/File:MicroPython_new_logo.svg) 

**More Links**

> [MicroPython (Wikipedia)](https://en.m.wikipedia.org/wiki/MicroPython)

> [Github Repo](https://github.com/micropython/micropython)

**Comment by gilbarbara** [comment]
Added in e6c61d4e86536e2ffa2834689a9f44e1d38019e0
Thanks
