### ISSUE TITLE
Add Fresh

### ISSUE THREAD

**Issue by Hyperx837** [gilbarbara/logos#544]
**[Fresh: The NextGen Web Framework](https://fresh.deno.dev)**

**An emerging web framework for deno that will very likely go mainstream production**

**[Source to SVG file from official GitHub repo](https://github.com/denoland/fresh/raw/main/www/static/logo.svg)**

**Comment by gilbarbara** [comment]
Added in f17b380deb6885848536a57763e98de27621cdbe
Thanks
