### ISSUE TITLE
Update TypeScript icon

### ISSUE THREAD

**Issue by KirillTregubov** [gilbarbara/logos#545]
**Name with link**
TypeScript icon [typescript-icon.svg](https://user-images.githubusercontent.com/31662934/178327528-64bdeeb1-a4c2-4a9c-a44a-e336f6c130c7.svg)

**Description**
I have uploaded `ts-logo-256.svg` provided in the latest [TypeScript Branding](https://www.typescriptlang.org/branding) asset pack. If you compare the version linked above to [the version on your repo](https://github.com/gilbarbara/logos/blob/master/logos/typescript-icon.svg), you will notice that their 'S' is different, showing they have changed their font (they have also added a border radius).

**Link to the vector file, preferably from an official source**
[TypeScript asset pack](https://www.typescriptlang.org/branding/typescript-design-assets.zip)

Thanks for your amazing work on the repo!

**Comment by gilbarbara** [comment]
Thanks mate!
It will be updated ASAP.

**Comment by gilbarbara** [comment]
Updated in ba9bfcadc31502f10917bb1b511b1d08825856f3
Thanks
