### ISSUE TITLE
Add Mantine

### ISSUE THREAD

**Issue by obillekyle** [gilbarbara/logos#546]
**Name with link**
Mantine https://mantine.dev

**Description**
Mantine is a React components and hooks library with native dark theme support and focus on usability, accessibility and developer experience, it has more than 120 customizable components and hooks to cover you in any situation.

**Link to the vector file, preferably from an official source**
[favicon.svg](https://mantine.dev/favicon.svg)
[Github](https://github.com/mantinedev/mantine/blob/master/docs/src/images)

**Comment by gilbarbara** [comment]
It was already in my backlog...

Added in f31ecd8b034658fd5b1dd40aa16614767aeaa9ee
Thanks
