### ISSUE TITLE
Update MongoDB

### ISSUE THREAD

**Issue by KirillTregubov** [gilbarbara/logos#547]
**Name with link**
MongoDB [mongodb.svg](https://mongodb.getbynder.com/web/25fa5732b9e81e6a/press-kit/?mediaId=EBDAA189-3FD9-4D40-AE7B489ECB6158C8)

**Description**
Hi it's me again! Sorry to bother, but I just discovered that MongoDB has also changed their [brand resources](https://www.mongodb.com/brand-resources).

**Link to the vector file, preferably from an official source**
Here is their [official media kit](https://mongodb.getbynder.com/web/25fa5732b9e81e6a/press-kit/) linked at the bottom of their [brand resources](https://www.mongodb.com/brand-resources) page.

Thanks again for your time and the quick response on my last issue!

**Comment by gilbarbara** [comment]
hey @KirillTregubov 

It's no bother at all, keep them coming!
I've already updated their logo locally and will upload it asap.

**Comment by KirillTregubov** [comment]
Haha will do, cheers!

**Comment by gilbarbara** [comment]
Updated in 652349ebbcb1c8a95d59bf36964a7d0fde643bfe
Thanks
