### ISSUE TITLE
Add Drools

### ISSUE THREAD

**Issue by boukadam** [gilbarbara/logos#548]
**Name with link**
Drools
https://www.drools.org/

**Description**
Drools is a Business Rules Management System (BRMS) solution.
As java developer, I used Drools since several years.

**Link to the vector file, preferably from an official source**
icon : https://design.jboss.org/jbossrules/logo/final/drools_icon.svg
logo : https://design.jboss.org/jbossrules/logo/final/drools_logo.svg

**Comment by gilbarbara** [comment]
This is a duplicate of your own rejected request #419

**Comment by boukadam** [comment]
I thought it was rejected because I had opened a lot of issues
is it drools that is the problem?

**Comment by gilbarbara** [comment]
Added in 11f54bac1b6dfad2cbd1c6da9f2245ec8b5ea22b
Thanks
