### ISSUE TITLE
Add Microsoft (symbol)

### ISSUE THREAD

**Issue by dungsil** [gilbarbara/logos#549]
**Name with link**
Microsoft

**Description**
I need a logo that only has a Microsoft icon
like a `google` and `google-icon`

**Link to the vector file, preferably from an official source**
https://docs.microsoft.com/en-us/azure/active-directory/develop/media/howto-add-branding-in-azure-ad-apps/ms-symbollockup_mssymbol_19.svg

**Comment by gilbarbara** [comment]
Added in b8f7d66ff934a70f78a850993286146656825d8b
Thanks
