### ISSUE TITLE
Add CodeClimate (Icon)

### ISSUE THREAD

**Issue by exoRift** [gilbarbara/logos#551]
**Name with link**
codeclimate-icon

**Description**
The CodeClimate logo icon ~~as opposed to the banner~~

**Link to the vector file, preferably from an official source**
Couldn't find an official SVG provided from branding, however, I COULD get this path from their [maintainability badge](https://api.codeclimate.com/v1/badges/a6122e76dcb42d834772/maintainability)

![badge](https://api.codeclimate.com/v1/badges/a6122e76dcb42d834772/maintainability)

```svg
    <g fill="#FFF" transform="translate(6 5)">
      <polygon points="11.135 0 8.018 3.089 9.872 4.926 11.135 3.674 14.718 7.226 16.571 5.389"/>
      <polygon points="7.518 3.893 5.613 2.065 .754 6.729 0 7.453 1.914 9.29 2.667 8.566 5.131 6.201 5.613 5.738 7.518 7.567 9.312 9.29 11.226 7.453 9.431 5.73"/>
    </g>
```

**Comment by gilbarbara** [comment]
Hey @exoRift 

The Code Climate [logo](https://github.com/gilbarbara/logos/blob/master/logos/codeclimate.svg) is already available.

**Comment by exoRift** [comment]
Apologies for reopening the issue, @gilbarbara , I thought I was clearer when I added "~~as opposed to the banner~~" to the description.

The logo you currently serve is a banner, not the actual logo itself (which is the progress chart-looking-thing)

**Comment by gilbarbara** [comment]
I'm not sure I understand what you mean.

If you navigate to https://codeclimate.com/, you'll see that we have the same logo in this repo. It's not a banner or badge.
Do you want to add the logomark (the icon) besides the full logo?

**Comment by exoRift** [comment]
Yes, the icon. Sorry for the confusion

**Comment by gilbarbara** [comment]
Added in b8f7d66ff934a70f78a850993286146656825d8b
Thanks
