### ISSUE TITLE
Add deviantart-icon

### ISSUE THREAD

**Issue by exoRift** [gilbarbara/logos#552]
**Name with link**
deviantart-icon

**Description**
The DeviantArt logo icon

**Link to the vector file, preferably from an official source**
Once again, could not find a link, but was able to snag it from the [branding page](https://deviantartads.com/#brand-partnerships)'s loading animation
![image](https://user-images.githubusercontent.com/20345400/185654110-41e7bfa9-b026-4bf4-b2aa-7782310c22df.png)

```svg
<svg viewBox="0 0 126.5 204" class="logo-mark"><path d="M126.5,112.3v50.9H63.9l-5.5,3.7l-17.5,33.4l-3.7,3.7H0h0v-37.1l37.5-71.5l-3.1-3.7H0V40.8h62.6l5.5-3.7            L85.6,3.7L89.3,0h37.2h0v37.1L89,108.5l3.1,3.7H126.5z"></path></svg>
```

```css
fill: #05cc47;
```

**Comment by gilbarbara** [comment]
Added in b8f7d66ff934a70f78a850993286146656825d8b
Thanks
