### ISSUE TITLE
Add GSAP aka Green Sock logo

### ISSUE THREAD

**Issue by Tiesco789** [gilbarbara/logos#553]
**Name with link**
GSAP aka Green Sock
https://greensock.com/

**Description**
I need this logo, both character and character with text.

**Link to the vector file, preferably from an official source**
https://greensock.com/uploads/set_resources_5/84c1e40ea0e759e3f1505eb1788ddf3c_greensock-logo.svg

**Comment by gilbarbara** [comment]
Added in 3f8b2dd45dac2ecde1cd40cc4146369226fe7507
Thanks
