### ISSUE TITLE
Add SurrealDB

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#554]
**Name with link**

[SurrealDB](https://surrealdb.com/)

[Github Repo](https://github.com/surrealdb/surrealdb) 

**Description**

SurrealDB is an end-to-end cloud native database for web, mobile, serverless, jamstack, backend, and traditional applications. SurrealDB reduces the development time of modern applications by simplifying your database and API stack, removing the need for most server-side components, allowing you to build secure, performant apps quicker and cheaper. SurrealDB acts as both a database and a modern, realtime, collaborative API backend layer. SurrealDB can run as a single server or in a highly-available, highly-scalable distributed mode - with support for SQL querying from client devices, GraphQL, ACID transactions, WebSocket connections, structured and unstructured data, graph querying, full-text indexing, geospatial querying, and row-by-row permissions-based access.

[SurrealDB in 100 seconds by Fireship](https://youtu.be/C7WFwgDRStM) 

**Link to the vector file, preferably from an official source**

[Black Logo](https://github.com/surrealdb/surrealdb/blob/main/img/black/logo.svg) 

[White Logo](https://github.com/surrealdb/surrealdb/blob/main/img/white/logo.svg)

**Comment by gilbarbara** [comment]
Added in 1f9332a66b7684f677cc29f1f59f5966f06742ff
Thanks
