### ISSUE TITLE
Add Chrome Web Store

### ISSUE THREAD

**Issue by jwr12135** [gilbarbara/logos#555]
**Name with link**

[Chrome Web Store](https://chrome.google.com/webstore)

**Description**

The Chrome Web Store icon (found at the top of the website).

**Link to the vector file, preferably from an official source**

The original icon (in the website) contains the full chrome SVG icon within (with the unshown portion clipped off). I went ahead and modified the original file's paths so the chrome icon is cut out without needing a clip element. Aside from that and some other optimizations, this file is the same SVG as the one on their website.

![Chrome Web Store Icon](https://user-images.githubusercontent.com/47087725/191130943-2634cb03-4246-4343-880e-d9e84cacaeb6.svg)

**Comment by gilbarbara** [comment]
Added in 1f9332a66b7684f677cc29f1f59f5966f06742ff
Thanks
