### ISSUE TITLE
Add reCAPTCHA

### ISSUE THREAD

**Issue by Waleed-KH** [gilbarbara/logos#556]
**Name with link**
[reCAPTCHA](https://developers.google.com/recaptcha)

**Description**
Google reCAPTCHA used by millions everyday

**Link to the vector file, preferably from an official source**
Logo: https://www.vectorlogo.zone/logos/google_recaptcha/google_recaptcha-official.svg
Icon: https://www.vectorlogo.zone/logos/google_recaptcha/google_recaptcha-icon.svg

couldn't find SVG on official source

**Comment by gilbarbara** [comment]
Added in 1f9332a66b7684f677cc29f1f59f5966f06742ff
Thanks

**Comment by Waleed-KH** [comment]
Can you also add the Icon: https://www.vectorlogo.zone/logos/google_recaptcha/google_recaptcha-icon.svg ? (that what I mainly use)
