### ISSUE TITLE
Add Storyblok

### ISSUE THREAD

**Issue by alvarosabu** [gilbarbara/logos#557]
**Name with link**
Headless CMS https://www.storyblok.com/ 

**Description**
Storyblok is an enterprise-level [Headless Content Management System](https://www.storyblok.com/tp/headless-cms-explained) with the [Visual Editor](https://www.storyblok.com/docs/editor-guides/visual-editor). The Visual Editor allows the editorial team to manage and organize the content visually and intuitively. The editorial team can assemble the content by dragging and dropping reusable components, preview the content in real-time, and manage images (and assets) without worrying about duplicating formats and resolutions.

**Link to the vector file, preferably from an official source**

https://a.storyblok.com/f/88751/x/f25a0afafb/storyblok-logo-brand-guidelines.pdf 

https://drive.google.com/drive/folders/1VIx4b-spIWntCaGP-137qdcBFiyMYkoT

**Comment by gilbarbara** [comment]
Added in 1f9332a66b7684f677cc29f1f59f5966f06742ff
Thanks
