### ISSUE TITLE
Add Adobe Substance 3D logos

### ISSUE THREAD

**Issue by JoJk0** [gilbarbara/logos#558]
**Name with link**
Adobe Substance 3D Collection
https://www.adobe.com/products/substance3d/3d-augmented-reality.html

**Description**
Newly added products into Adobe collection. 
I would personally need it to my *Tech Stack* portfolio section.

**Adobe Substance 3D Assets**
https://www.adobe.com/content/dam/cc/icons/sb_assets_appicon_256.svg

**Adobe Substance 3D  Designer**
https://www.adobe.com/content/dam/cc/icons/ds_appicon_256.svg

**Adobe Substance 3D  Sampler**
https://www.adobe.com/content/dam/cc/icons/sa_appicon_256.svg

**Adobe Substance 3D  Painter**
https://www.adobe.com/content/dam/cc/icons/pt_appicon_256.svg

**Adobe Substance 3D  Stager**
https://www.adobe.com/content/dam/cc/icons/sg_appicon_256.svg

**Comment by gilbarbara** [comment]
Cleaning
