### ISSUE TITLE
Add qbittorrent

### ISSUE THREAD

**Issue by juls0730** [gilbarbara/logos#563]
**Name with link**
[qbittorrent](https://www.qbittorrent.org/)

**Description**
qbittorrent is a widely used bittorrent client

**Link to the vector file, preferably from an official source**
[qbittorrent-icon](https://upload.wikimedia.org/wikipedia/commons/6/66/New_qBittorrent_Logo.svg)

**Comment by gilbarbara** [comment]
hey @juls0730 

Apps are out of scope for this collection, save some rare exceptions.
