### ISSUE TITLE
Update Nuxt Logo

### ISSUE THREAD

**Issue by Atinux** [gilbarbara/logos#564]
We updated our logo with the release of Nuxt 3:

Logo:
![full-logo-green-dark](https://user-images.githubusercontent.com/904724/206157996-35eff5cc-c992-40ab-873c-a1c9d325e181.svg)

Icon:
![icon-green](https://user-images.githubusercontent.com/904724/206158068-865af964-44ea-4aa8-99e9-fc96e6d6e447.svg)

Thank you again for what you are doing ❤️

**Comment by gilbarbara** [comment]
Updated in d5a7437d826f5ef20d2815f7bed24d90ef113de2
Thanks
