### ISSUE TITLE
Add svgporn.com logo

### ISSUE THREAD

**Issue by Visual-Dawg** [gilbarbara/logos#565]
**Name with link**
https://svgporn.com/

**Description**
The logo of SVG porn

**Link to the vector file, preferably from an official source**
I could only find an inline version, so here its:
`<svg width="512px" height="444px" viewBox="0 0 512 444" version="1.1" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid"><title>SVG PORN</title><g><path d="M381.304204,0 L512,222.468072 L381.276223,443.613161 L128.002985,443.613161 L0,222.467691 L127.975146,0 L381.304204,0 Z M82.2689549,333.439347 L137.00407,428.003002 L247.639081,428.003002 L302.593184,333.656426 L82.2689549,333.439347 Z M376.544851,237.708581 L265.704914,428.003002 L372.370229,428.003002 L430.007696,330.49732 L376.544851,237.708581 Z M194.802106,134.055659 L143.804203,222.536481 L198.825625,317.943825 L301.788285,318.045291 L194.802106,134.055659 Z M71.8091724,128.942844 L18.0225754,222.443588 L73.2282335,317.820407 L180.795891,317.926263 L71.8091724,128.942844 Z M436.852263,125.370556 L329.834864,125.370556 L439.130858,315.063262 L493.880966,222.443588 L436.852263,125.370556 Z M311.818788,125.370556 L207.809759,125.370556 L315.769622,311.034866 L367.561204,222.116958 L311.818788,125.370556 Z M245.053649,15.6101594 L137.00407,15.6101594 L80.8074537,113.300001 L134.793239,206.9112 L245.053649,15.6101594 Z M372.370229,15.6101594 L263.070699,15.6101594 L208.805395,109.760397 L427.681782,109.760397 L372.370229,15.6101594 Z" fill="currentColor"></path></g></svg>`

**Comment by gilbarbara** [comment]
Why do you want to add it?

**Comment by Visual-Dawg** [comment]
I thought it would be a fun suggestion. No real reason.
Designers might want to add it to resource lists though
