### ISSUE TITLE
Add SAP , S4Hana logos

### ISSUE THREAD

**Issue by npiper** [gilbarbara/logos#566]
**Name with link**
SAP 
https://www.sap.com/uk/index.html

https://en.wikipedia.org/wiki/SAP

**Description**
SAP SE is a German  software company providing ERP type software.

**Link to the vector file, preferably from an official source**
https://commons.wikimedia.org/wiki/File:SAP_2011_logo.svg

**Comment by gilbarbara** [comment]
Added in 1f372be75689d73cae89b6de808149b606b879e1
Thanks
