### ISSUE TITLE
Add HashiCorp

### ISSUE THREAD

**Issue by porkbeans** [gilbarbara/logos#569]
**Name with link**
HashiCorp
https://www.hashicorp.com/

**Description**
Software company.
Developing Consul, Nomad, Packer, Vagrant, Terraform, Vault, ...etc.

**Link to the vector file, preferably from an official source**
https://www.hashicorp.com/brand#logo
1. Get a zip file with `Download Logo Assets` button.
1. SVG files in the zip file:
    - `Corporate/Logo/Primary_Horizontal/RGB/SVG/*.svg`
    - `Corporate/Logo/Secondary_Vertical/RGB/SVG/*.svg`
    - `Corporate/Logomark/RGB/SVG/*.svg`

**Comment by gilbarbara** [comment]
Added in 1f372be75689d73cae89b6de808149b606b879e1
Thanks
