### ISSUE TITLE
node-sass

### ISSUE THREAD

**Issue by httpete-ire** [gilbarbara/logos#57]
would be cool to have the node-sass logo, can be found [here](https://camo.githubusercontent.com/f1e23b7f0efb3e6acf2b5a11c0379e5c51cc911b/68747470733a2f2f7261776769742e636f6d2f736173732f6e6f64652d736173732f6d61737465722f6d656469612f6c6f676f2e737667)

**Comment by gilbarbara** [comment]
Added f2df6adc70880c6e8431c889401103371232fede
