### ISSUE TITLE
Add Edgio Logo

### ISSUE THREAD

**Issue by rishi-raj-jain** [gilbarbara/logos#571]
**Name with link**

Edgio, https://edg.io/

**Description**

We're sponsoring Nuxt.js, and need to get our logo there on their core: https://nuxt.com/docs/getting-started/deployment#supported-hosting-providers:~:text=heroku-,layer0,-Netlify. This will be a dependency for Nuxt (framework) PR: https://github.com/nuxt/framework/pull/9900

**Link to the vector file, preferably from an official source**

I'm, Technical CSM at Edgio. Here are the downloaded svgs right from the our branding source.

Link: https://a.storyblok.com/f/117912/x/5e81fb1276/edgio_logo_final_rgb_black_background.svg
![Edgio_Logo_Final_RGB_Black_Background](https://a.storyblok.com/f/117912/x/5e81fb1276/edgio_logo_final_rgb_black_background.svg)

Link: https://a.storyblok.com/f/117912/x/b36af13d50/edgio_logo_final_rgb_gradient_background.svg
![Edgio_Logo_Final_RGB_Gradient_Background](https://a.storyblok.com/f/117912/x/b36af13d50/edgio_logo_final_rgb_gradient_background.svg)

**Comment by gilbarbara** [comment]
Hey @rishi-raj-jain 

The logos you attached include raster images for the gradient, which isn't acceptable.
I could add the wordmark and use the E as the icon. Would that work for you?
This is a curated list of logos, and I appreciate that Edgio supports open-source, but I can't add raster images.

**Comment by rishi-raj-jain** [comment]
@gilbarbara 

Which format is the ideal one? I can ask the designers from our team to make one for you whichever works.

**Comment by gilbarbara** [comment]
Added in c3bbf0e707fa9d7940c2c7b84ac72fa954a444c9
Thanks

**Comment by rishi-raj-jain** [comment]
Appreciate all of your time and work! @gilbarbara
