### ISSUE TITLE
Add Supabase

### ISSUE THREAD

**Issue by thibaudbrault** [gilbarbara/logos#576]
**Name with link**
Supabase: https://supabase.com/  

**Description**
Supabase is an open source Firebase alternative  

**Link to the vector file, preferably from an official source**
https://supabase.com/brand-assets

**Comment by gilbarbara** [comment]
Hey @thibaudbrault 
Supabase is already in the [collection](https://github.com/search?q=repo%3Agilbarbara%2Flogos%20supabase&type=code)
