### ISSUE TITLE
Add zoom

### ISSUE THREAD

**Issue by m0dch3n** [gilbarbara/logos#577]
**Name with link**
Zoom: https://zoom.us/

**Description**
Zoom is a video call provider

**Link to the vector file, preferably from an official source**

Official: https://brand.zoom.us/brand-system/public
Wikipedia: https://commons.wikimedia.org/wiki/File:Zoom_Communications_Logo.svg

**Comment by gilbarbara** [comment]
Added in c3bbf0e707fa9d7940c2c7b84ac72fa954a444c9
Thanks
