### ISSUE TITLE
Add Mautic

### ISSUE THREAD

**Issue by Yann-J** [gilbarbara/logos#579]
**[Mautic](https://www.mautic.org/)**

**Description**

Mautic is a powerful open-source marketing automation solution, designed to build customer contact workflows across web, email, and text messaging.

**Link to the vector file, preferably from an official source**

All official source files are [here](https://www.mautic.org/about/logos-and-graphics). However, I've noticed the icon svg has the wrong color (the circle is white #fff instead of the blue #34e5e9e). I've attached a corrected version.

![mautic](https://user-images.githubusercontent.com/59641363/219562872-702be1e9-526b-4dd1-94de-f0d1d80476cd.svg)

**Comment by gilbarbara** [comment]
Added in 952e2c69d7bfc699d9bd60f65cf5efb0c623c9d6
Thanks
