### ISSUE TITLE
Add Google Workspace

### ISSUE THREAD

**Issue by 0xThiebaut** [gilbarbara/logos#582]
**Name with link**
[Google Workspace](https://workspace.google.com/)

**Description**
Google's enterprise suite of tools (Gmail, Calendar, Meet, Chat, Drive, Docs, Sheets, Slides, ...) and IdP (Identity Provider).

**Link to the vector file, preferably from an official source**
https://workspace.google.com/static/img/google-workspace-logo.svg

**Comment by gilbarbara** [comment]
Added in c3bbf0e707fa9d7940c2c7b84ac72fa954a444c9
Thanks
