### ISSUE TITLE
Add JSON-LD Logo

### ISSUE THREAD

**Issue by npiper** [gilbarbara/logos#583]
**JSON-LD**

https://json-ld.org/

**Description**

JSON-LD is a lightweight Linked Data format. It is easy for humans to read and write.

**Link to the vector file, preferably from an official source**

https://commons.wikimedia.org/wiki/File:JSON-LD.svg

**Comment by gilbarbara** [comment]
Added in 952e2c69d7bfc699d9bd60f65cf5efb0c623c9d6
Thanks
