### ISSUE TITLE
Add new Netlify Logo

### ISSUE THREAD

**Issue by manniL** [gilbarbara/logos#584]
**Name with link**

[Netlify](https://www.netlify.com/press/#logos)

**Description**

Rebranded logo for Netlify, ideally all three versions - monogram, encapsulated, full

**Link to the vector file, preferably from an official source**

https://www.netlify.com/press/#logos

**Comment by gilbarbara** [comment]
Updated in f419323800eeed0e76b370bb65c8e84159765e72
Thanks
