### ISSUE TITLE
Add AsyncAPI Logo

### ISSUE THREAD

**Issue by npiper** [gilbarbara/logos#585]
**AsyncAPI**

Open-Source tools to easily build and maintain your event-driven architecture. All powered by the AsyncAPI specification, the industry standard for defining asynchronous APIs.

https://www.asyncapi.com/

**Description**

**Link to the vector file, preferably from an official source**

https://images.opencollective.com/asyncapi/19c6734/logo/256.png
https://www.asyncapi.com/

![asyncAPI](https://user-images.githubusercontent.com/436314/227385748-3945a0d0-dde3-4a86-af0f-d84bf1bcf0b3.svg)

**Comment by gilbarbara** [comment]
Added in 952e2c69d7bfc699d9bd60f65cf5efb0c623c9d6
Thanks
