### ISSUE TITLE
Add OpenAPI logo

### ISSUE THREAD

**Issue by npiper** [gilbarbara/logos#586]
**OpenAPI**

https://github.com/OAI/OpenAPI-Specification

**Description**

The OpenAPI Specification is a community-driven open specification within the [OpenAPI Initiative](https://www.openapis.org/), a Linux Foundation Collaborative Project.

**Link to the vector file, preferably from an official source**
https://github.com/OAI/OpenAPI-Style-Guide/blob/9bc33ec40f1d42ee0edfcb420a2435c657ada220/graphics/vector/OpenAPI_Logo_Stacked_Pantone.svg

https://github.com/OAI/Documentation/blob/main/assets/images/OpenAPI_Logo_Pantone-1.png
https://github.com/OAI/OpenAPI-Style-Guide/blob/9bc33ec40f1d42ee0edfcb420a2435c657ada220/graphics/vector/OpenAPI_Logo_Black.svg

**Comment by gilbarbara** [comment]
Added in c3bbf0e707fa9d7940c2c7b84ac72fa954a444c9
Thanks
