### ISSUE TITLE
Update Google Play

### ISSUE THREAD

**Issue by Nitrrine** [gilbarbara/logos#587]
**Name with link**
Google Play Logo 

**Description**
Google Play updated logo in 2022

**Link to the vector file, preferably from an official source**
Logo: https://upload.wikimedia.org/wikipedia/commons/7/7a/Google_Play_2022_logo.svg
Icon: https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_Play_2022_icon.svg

**Comment by gilbarbara** [comment]
Duplicate #573

**Comment by Nitrrine** [comment]
Hello, this is Google **Play**, Not Google **Pay**

**Comment by gilbarbara** [comment]
Oh, okay

**Comment by gilbarbara** [comment]
Updated in f419323800eeed0e76b370bb65c8e84159765e72
Thanks
