### ISSUE TITLE
Update Bing

### ISSUE THREAD

**Issue by Nitrrine** [gilbarbara/logos#588]
**Name with link**
Bing Logo 2023

**Description**

**Link to the vector file, preferably from an official source**
Logo: https://upload.wikimedia.org/wikipedia/commons/e/e3/Bing_Fluent_Logo_Text.svg
Icon: https://upload.wikimedia.org/wikipedia/commons/9/9c/Bing_Fluent_Logo.svg

**Comment by gilbarbara** [comment]
Updated in f419323800eeed0e76b370bb65c8e84159765e72
Thanks
