### ISSUE TITLE
ArangoDB multi-model Database

### ISSUE THREAD

**Issue by ifcologne** [gilbarbara/logos#59]
Hi, could you please add the ArangoDB logo as well?

https://www.arangodb.com/wp-content/themes/arangodb-wp-theme/images/logos/arangodb-logo.ai
https://www.arangodb.com/wp-content/themes/arangodb-wp-theme/images/logos/arangodb-logo.eps
![2014-10-24_arangodb_logo_rgb_01](https://cloud.githubusercontent.com/assets/2922081/8645135/eed9cf54-2944-11e5-9955-42daaaee90c3.png)

**Comment by gilbarbara** [comment]
Yes, definitely, I was searching it yesterday.
:+1:

**Comment by gilbarbara** [comment]
Added f2df6adc70880c6e8431c889401103371232fede
