### ISSUE TITLE
Update Firefox logo

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#592]
Last version from [mozilla.org](https://www.mozilla.org/media/protocol/img/logos/firefox/browser/logo-word-hor.7ff44b5b4194.svg):

![](https://www.mozilla.org/media/protocol/img/logos/firefox/browser/logo-word-hor.7ff44b5b4194.svg)

**Comment by gilbarbara** [comment]
Updated in 608007b99fab1d55be5de9f9ec2c75bcc80a438c
Thanks
