### ISSUE TITLE
Update C# logo

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#593]
Current C# logo not look like similar C and C++ logos, I propose update it:

![](https://cdn.worldvectorlogo.com/logos/c--4.svg)

**Comment by gilbarbara** [comment]
Hey @PonomareVlad 

There's no official logo for C sharp, so it's a personal preference.
I'm using the [Wikipedia](https://en.wikipedia.org/wiki/C_Sharp_%28programming_language%29) version and I'll stick to it for now.

Thanks anyway
