### ISSUE TITLE
Add Behance logo

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#594]
https://www.behance.net

![](https://upload.wikimedia.org/wikipedia/commons/c/c5/Behance_logo.svg)

**Comment by gilbarbara** [comment]
Hey @PonomareVlad 

Please use the issue template to make it easy to get the logo added.

**Comment by PonomareVlad** [comment]
@gilbarbara sorry, fixed 😬

**Comment by gilbarbara** [comment]
Hey @PonomareVlad 
We already have Behance on the site. Is this any different?

**Comment by PonomareVlad** [comment]
I’m sorry, I didn’t specify what I mean, additional icon variant that consists of the first two letters.

Like this:

https://a5.behance.net/ce27ad7fbea0e0393442e24d419b0d4b4a4d2010/img/site/favicon.ico

**Comment by gilbarbara** [comment]
They don't use the favicon as a brand asset, as I couldn't find any reference on their website or brand guidelines.
Feel free to re-open the issue if you find any official usage and a vector file.
