### ISSUE TITLE
Update Windows logo to 11 version

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#595]
Also I think it would be nice to add a start menu icon:

[Source](https://www.figma.com/community/file/1083153685442292050/Windows-11-UI-Kit)

![Windows](https://user-images.githubusercontent.com/2877584/229524949-99cb302a-ceb7-4a4e-ae33-a19b8b9ad258.svg)

**Comment by gilbarbara** [comment]
Updated in 608007b99fab1d55be5de9f9ec2c75bcc80a438c
Thanks
