### ISSUE TITLE
Add Node.js icon

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#596]
I'm not sure this will be a big need, but I suggest considering it as an alternative icon:

![nodejs2](https://user-images.githubusercontent.com/2877584/229525885-d6f06474-d560-4f34-8b63-cae8f7265008.svg)

**Comment by gilbarbara** [comment]
Added in 608007b99fab1d55be5de9f9ec2c75bcc80a438c
Thanks
