### ISSUE TITLE
Add looppanel logo

### ISSUE THREAD

**Issue by VartikaLooppanel** [gilbarbara/logos#598]
Looppanel

Looppanel is a UX Research repository tool that automatically records your calls, transcribes them, and centralizes all your research data in one place.

https://www.looppanel.com/

Link to the vector file 
https://github.com/VartikaLooppanel/logo/blob/main/Loop%20logo%20black%201.svg

![Loop logo black 1](https://user-images.githubusercontent.com/129509220/229560777-04f297f8-42ec-43e5-b78c-78088af4f044.svg)

**Comment by gilbarbara** [comment]
Hey @VartikaLooppanel 

This isn't a vector file, just an SVG wrapper for a PNG.
We can't accept raster images.
