### ISSUE TITLE
Add new AMEX logo

### ISSUE THREAD

**Issue by asonnleitner** [gilbarbara/logos#599]
American Express Digital Logo

This static digital logo is great for displaying on your website and online checkout page, or for creating online advertising that lets customers know you accept American Express card payments.

[Direct Download](https://www.americanexpress.com/content/dam/amex/us/merchant/supplies-uplift/product/digital/WEBLOGO1.zip) | https://www.americanexpress.com/en-gb/business/merchant/supplies/details/?pid=WEBLOGO1

**Comment by gilbarbara** [comment]
Added in 608007b99fab1d55be5de9f9ec2c75bcc80a438c
Thanks
