### ISSUE TITLE
Update Instagram Logo

### ISSUE THREAD

**Issue by IsraelOrtuno** [gilbarbara/logos#601]
Current instagram logo is being shown in BLACK meanwhile Twitch/Twitter and so many others include their branding color. I think that the best option is to add the Instagram icon in its gradient version.

The Logo pack from meta itself includes the three versions (gradient, black and white).
https://about.meta.com/brand/resources/instagram/instagram-brand/

**Comment by gilbarbara** [comment]
Hey @IsraelOrtuno 

The gradient logo uses a raster image, which isn't acceptable for this collection. So we use the black option instead.

Thanks anyway!
