### ISSUE TITLE
Add IDs to logos

### ISSUE THREAD

**Issue by Jaaneek** [gilbarbara/logos#604]
I can see that the Icons, names and even short names sometimes change. Could we have ID with every icon to make it easier to track changes? Thanks a lot for you hard work!

**Comment by gilbarbara** [comment]
Hey @Jaaneek 

Are you referring to the logos.json?
Shortname never changes. You can use it as an ID.
Names and files can change. Nothing to do about it.

**Comment by Jaaneek** [comment]
Thanks! I will use short names, I really appreciate your work! <3
