### ISSUE TITLE
Add Apache Flink

### ISSUE THREAD

**Issue by mhjtrifork** [gilbarbara/logos#605]
**Name with link**
Apache Flink https://flink.apache.org/

**Description**
Apache Flink is an open source stream processing framework with powerful stream- and batch-processing capabilities.

**Link to the vector file, preferably from an official source**
Logos: https://flink.apache.org/material/

**Comment by gilbarbara** [comment]
Added in bea0759cf5fbfaad7e92e6032ff9481dd82de561
Thanks
