### ISSUE TITLE
Add Opensearch

### ISSUE THREAD

**Issue by mhjtrifork** [gilbarbara/logos#606]
**Name with link**
Opensearch: https://opensearch.org/

**Description**
OpenSearch is a scalable, flexible, and extensible open-source software suite for search, analytics, and observability applications licensed under Apache 2.0.

**Link to the vector file, preferably from an official source**
https://opensearch.org/trademark-brand-policy.html#logo

**Comment by gilbarbara** [comment]
Added in bea0759cf5fbfaad7e92e6032ff9481dd82de561
Thanks
