### ISSUE TITLE
Bitrise logo

### ISSUE THREAD

**Issue by ricardopereira** [gilbarbara/logos#61]
![bitrise_logo_bw](https://cloud.githubusercontent.com/assets/3541185/8702620/bb82b67a-2b10-11e5-8c15-d9752e550a76.png)

**Comment by ricardopereira** [comment]
SVG: https://dl.dropboxusercontent.com/u/11377305/tmp/bitrise_logo_bg.svg

**Comment by ricardopereira** [comment]
SVG with description: https://dl.dropboxusercontent.com/u/11377305/tmp/bitrise_logo_transparent.svg

**Comment by ricardopereira** [comment]
Thanks :+1:

**Comment by gilbarbara** [comment]
Nice!
Added 2edbd5fe52f7a4f640bcce979aa52e5856bc6656
