### ISSUE TITLE
Add Internet Computer

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#616]
[World Computer blockchain that reimagines the internet as an infinite smart contract platform.](https://internetcomputer.org)

[![Logo](https://internetcomputer.org/img/IC_logo_horizontal.svg)](https://internetcomputer.org/img/IC_logo_horizontal.svg)

**Comment by gilbarbara** [comment]
Added in 29e8719bf78915c7a82a26a6c203f53c4cb8fff2
Thanks
