### ISSUE TITLE
Add Xcode

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#618]
[Source from this collection](https://github.com/devicons/devicon)

[![Xcode](https://github.com/devicons/devicon/raw/master/icons/xcode/xcode-original.svg)](https://github.com/devicons/devicon/blob/master/icons/xcode/xcode-original.svg)

**Comment by gilbarbara** [comment]
Added in a863e8bc9785134a78b119c99d24f983c2ff44ef
Thanks!
