### ISSUE TITLE
DuckDuckGo logo

### ISSUE THREAD

**Issue by syxanash** [gilbarbara/logos#62]
![ddg](https://duckduckgo.com/assets/logo_homepage.normal.v107.svg)

how about [DuckDuckGo](https://duckduckgo.com/) search engine logo?

https://duckduckgo.com/assets/logo_homepage.normal.v107.svg

**Comment by gilbarbara** [comment]
Added fc2976afab04ad40f1db4ba37b2b1217301f9595
Thanks!
