### ISSUE TITLE
Add OrangeFox

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#621]
[OrangeFox Recovery is one of the most popular custom recoveries, with amazing additional features, fixes and a host of supported devices.](https://wiki.orangefox.tech/en/home)

[![OrangeFox](https://orangefox.download/images/logo.svg)](https://orangefox.download/images/logo.svg)

**Comment by gilbarbara** [comment]
Hey @PonomareVlad 

Apps are out of scope, save for some rare exceptions.
