### ISSUE TITLE
Update SolidJS

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#622]
### Current:
[![Current](https://github.com/gilbarbara/logos/raw/main/logos/solidjs.svg)](https://github.com/gilbarbara/logos/blob/main/logos/solidjs.svg)

### Official:
[![Official](https://upload.wikimedia.org/wikipedia/commons/7/76/Logo_SolidJS.svg)](https://upload.wikimedia.org/wikipedia/commons/7/76/Logo_SolidJS.svg)

**Comment by gilbarbara** [comment]
Updated in 9e963c07045f9da1fadd4ce0425b5cbaa8ee94a7
Thanks

**Comment by PonomareVlad** [comment]
@gilbarbara It looks like the gradient of the icon has not changed, and still differs from the official version 🙃

**Comment by gilbarbara** [comment]
@PonomareVlad 
I've updated both the wordmark and the icon.

This is what I'm getting:
<img width="1106" alt="CleanShot 2023-05-10 at 09 01 28@2x" src="https://github.com/gilbarbara/logos/assets/31954/35ffc121-3fe4-4da0-b603-4a27b35dd5a6">

Try to clean your browser cache.

**Comment by PonomareVlad** [comment]
[I mean, there are no visual differences in the logo icon:](https://github.com/gilbarbara/logos/commit/9e963c07045f9da1fadd4ce0425b5cbaa8ee94a7#diff-206bf042e2735eb08b0ddf5ce92cc79800269bec027ebb93a8792cfcb3f4eb5d)

![Снимок экрана 2023-05-11 в 11 52 07](https://github.com/gilbarbara/logos/assets/2877584/8935911b-30d8-4807-9eff-6c17bc8499b1)

[But, the official version has differences (pay attention to the colors of the gradient):](https://www.solidjs.com)

![Снимок экрана 2023-05-11 в 11 51 21](https://github.com/gilbarbara/logos/assets/2877584/cb0f3854-e243-4014-a4cf-fed45c6400be)

**Comment by gilbarbara** [comment]
Updated in 37b8072c16c86eff8f7aff83d249ed4f722b693c
