### ISSUE TITLE
Add Obsidian

### ISSUE THREAD

**Issue by NomarCub** [gilbarbara/logos#623]
**Name with link**
Obsidian
https://obsidian.md/

**Description**
Obsidian is a personal knowledge base and note-taking software application that operates on Markdown files. It allows users to make internal links for notes and then to visualize the connections as a graph.

**Link to the vector file, preferably from an official source**
https://commons.wikimedia.org/wiki/File:Obsidian_software_logo.svg

**Comment by gilbarbara** [comment]
I usually don't add apps, but I think Obsidian is a valid option.

Added in a863e8bc9785134a78b119c99d24f983c2ff44ef
Thanks!

**Comment by NomarCub** [comment]
Hi!
Thanks!
Unfortunately the Obsidian logo changed *just* recently, for the first time in years.
https://obsidian.md/blog/new-obsidian-icon/
https://obsidian.md/brand
https://commons.m.wikimedia.org/wiki/File:2023_Obsidian_logo.svg
https://www.figma.com/community/file/1246118009912598137/Obsidian-Logo-and-App-Icons

**Comment by gilbarbara** [comment]
Updated!
