### ISSUE TITLE
Add Google Play Console

### ISSUE THREAD

**Issue by Nitrrine** [gilbarbara/logos#624]
**Name with link**
Play Console

**Description**
Google updated Play Console logo in 2023

**Link to the vector file, preferably from an official source**
Icon: https://github.com/gilbarbara/logos/assets/43351072/af625296-b925-409b-88bc-46bb53731f0e (I don`t find svg file so i converted svg text from official page to file)

Wordmark: https://www.gstatic.com/acx/play/console/play_console_ui_20230511_0240_RC01/main/play.console.ui.common.images/logos/navigation_menu_2023.svg

**Comment by gilbarbara** [comment]
Added in a863e8bc9785134a78b119c99d24f983c2ff44ef
Thanks!
