### ISSUE TITLE
Add Modrinth

### ISSUE THREAD

**Issue by Nitrrine** [gilbarbara/logos#625]
**Name with link**
Modrinth (https://modrinth.com)

**Description**
Modrinth is a Minecraft mod distribution platform

**Link to the vector file, preferably from an official source**
Logo`s taken from their official GitHub Repository
Icon: https://raw.githubusercontent.com/modrinth/art/5f7653034c85cc0bbf45d63bbcb167c624b7374b/Branding/Mark/mark-light.svg
Wordmark: https://raw.githubusercontent.com/modrinth/art/5f7653034c85cc0bbf45d63bbcb167c624b7374b/Branding/Wordmark/wordmark-light.svg

**Comment by gilbarbara** [comment]
Hey @Nitrrine 
I usually don't add logos related to games.
Thanks for your submission anyway.
