### ISSUE TITLE
Add Google Bard

### ISSUE THREAD

**Issue by Nitrrine** [gilbarbara/logos#626]
**Name with link**
Bard (https://bard.google.com)

**Description**
Bard is a conversational generative artificial intelligence chatbot developed by Google

**Link to the vector file, preferably from an official source**
Icon: https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg

**Comment by gilbarbara** [comment]
Added in a863e8bc9785134a78b119c99d24f983c2ff44ef
Thanks!
