### ISSUE TITLE
CHART.JS

### ISSUE THREAD

**Issue by IshwaranRudhara** [gilbarbara/logos#627]
**Name with link**
Chart.Js ( https://www.chartjs.org/ )
**Description**

Chart.js
Simple yet flexible JavaScript charting library for the modern web

**Link to the vector file, preferably from an official source**
[ https://www.chartjs.org/img/chartjs-logo.svg ]

**Comment by gilbarbara** [comment]
Added in 29e8719bf78915c7a82a26a6c203f53c4cb8fff2
Thanks
