### ISSUE TITLE
Add Pulumi

### ISSUE THREAD

**Issue by snilan** [gilbarbara/logos#628]
**Name with link**
Pulumi
https://www.pulumi.com/

**Description**
An infrastructure as code tool/platform, similar to AWS CDK or Terraform

**Link to the vector file, preferably from an official source**
https://www.pulumi.com/images/logo/logo-on-white.svg

**Comment by gilbarbara** [comment]
Added in da96ad61116f1c9178dee389ae55254277a45eb3
Thanks
