### ISSUE TITLE
Add Shadowsocks

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#632]
https://shadowsocks.org

[![Shadowsocks](https://upload.wikimedia.org/wikipedia/commons/f/f5/Shadowsocks-Logo.svg)](https://upload.wikimedia.org/wikipedia/commons/f/f5/Shadowsocks-Logo.svg)

**Comment by gilbarbara** [comment]
Hey @PonomareVlad 
The website doesn't use the logo, and the organization logo is quite different.
What's the source for it?

**Comment by PonomareVlad** [comment]
@gilbarbara [Wikimedia](https://commons.m.wikimedia.org/wiki/File:Shadowsocks-Logo.svg)
