### ISSUE TITLE
Add Meta logo

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#633]
https://about.meta.com

[![Meta](https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg)](https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg)

**Comment by gilbarbara** [comment]
Added in 52addcaa18dfecb4df77f3ee0753dca6b98187ad
Thanks
