### ISSUE TITLE
Add VMware

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#634]
https://www.vmware.com

[![VMware](https://upload.wikimedia.org/wikipedia/commons/9/9a/Vmware.svg)](https://commons.wikimedia.org/wiki/File:Vmware.svg)

**Comment by gilbarbara** [comment]
Hey @PonomareVlad 

I was on the fence about it since VMware is known for its emulator.
However, I just saw they have cloud solutions, so it fits the requirements for this collection.

**Comment by gilbarbara** [comment]
Added in 29e8719bf78915c7a82a26a6c203f53c4cb8fff2
Thanks
