### ISSUE TITLE
Add Effector

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#636]
https://effector.dev

[![Effector](https://raw.githubusercontent.com/effector/effector/master/website/client/static/img/comet.svg)](https://github.com/effector/effector/blob/master/website/client/static/img/comet.svg)

**Comment by Shiyan7** [comment]
Any news?(

**Comment by gilbarbara** [comment]
@Shiyan7 No. 🤣

**Comment by gilbarbara** [comment]
Added in cfa9aba939395a50b888e91e29ed1359abc7e986
Thanks
