### ISSUE TITLE
Add more Cloudflare logos

### ISSUE THREAD

**Issue by Nitrrine** [gilbarbara/logos#637]
**Name with link**
Cloudflare (https://cloudflare.com/)

**Description**
Cloudflare is a global network designed to make everything you connect to the Internet secure, private, fast, and reliable.

**Link to the vector file, preferably from an official source**
(SVG from official brand kit)
Horizontal:
![CF_logo_horizontal_blktype](https://github.com/gilbarbara/logos/assets/43351072/b349a283-6fbc-4a41-afea-7741fbf498bf)

Stacked:
![CF_logo_stacked_blktype](https://github.com/gilbarbara/logos/assets/43351072/e83633a6-5e86-4e67-90c1-8da39ba35978)

**Comment by gilbarbara** [comment]
Added in 5d365d6566feda9301b95dffa57825728410ce01
