### ISSUE TITLE
Add Jellyfin

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#639]
**Name with link**
[Jellyfin](https://jellyfin.org/)

[Github Profile](https://github.com/jellyfin)

**Description**
The Free Software Media System

Jellyfin is the volunteer-built media solution that puts you in control of your media. Stream to any device from your own server, with no strings attached. Your media, your server, your way.

**Link to the vector file, preferably from an official source**
[SVG Collection](https://github.com/jellyfin/jellyfin-ux/tree/master/branding/SVG)

[Branding Page](https://jellyfin.org/docs/general/contributing/branding/#logo)

**Comment by gilbarbara** [comment]
Hey @Redxtorm 
This is out of the scope for this repo.
