### ISSUE TITLE
Composer logo?

### ISSUE THREAD

**Issue by Hywan** [gilbarbara/logos#64]
Hello :-),

Could be awesome to have the [Composer logo](http://getcomposer.org/) in SVG here:

![Composer logo](https://getcomposer.org/img/logo-composer-transparent.png)

Thoughts?

/cc @Seldaek

**Comment by gilbarbara** [comment]
hey,
Yeah, I want to add it too but couldn't find a vector version of it.

**Comment by Hywan** [comment]
@gilbarbara We can also ping @naderman.

**Comment by royduin** [comment]
See: https://github.com/composer/composer/issues/4403

**Comment by gilbarbara** [comment]
@royduin Sweet!
I started converting it to vector but there were too many details to fix.

**Comment by Seldaek** [comment]
Here you go https://dl.dropboxusercontent.com/u/1634226/composer_original.svg

**Comment by gilbarbara** [comment]
@Seldaek Sweet! Thanks

**Comment by Hywan** [comment]
\o/

**Comment by gilbarbara** [comment]
Added finally! a5ed2105625c134e9284e0dba61690f6b0d092a5
Thanks
