### ISSUE TITLE
Add wordmark-less DigitalOcean icon

### ISSUE THREAD

**Issue by kidonng** [gilbarbara/logos#641]
**Name with link**

DigitalOcean: https://www.digitalocean.com/

**Description**

I'm asking for a wordmark-less version, similar to how other logos come with both a full version and an icon only version (e.g. [Google](https://github.com/gilbarbara/logos/blob/main/logos/google-domains.svg) [Domains](https://github.com/gilbarbara/logos/blob/main/logos/google-domains-icon.svg)).

**Link to the vector file, preferably from an official source**

https://github.com/gilbarbara/logos/blob/main/logos/digital-ocean.svg

**Comment by gilbarbara** [comment]
Added in 5d365d6566feda9301b95dffa57825728410ce01
