### ISSUE TITLE
Add Faker

### ISSUE THREAD

**Issue by amalrkc** [gilbarbara/logos#646]
**[Faker](https://fakerjs.dev/)**

**[Github repo](https://github.com/faker-js/faker)**

**Generate massive amounts of fake (but realistic) data for testing and development.**

**[Vector file](https://fakerjs.dev/logo.svg)**

**Comment by gilbarbara** [comment]
Added in 29e8719bf78915c7a82a26a6c203f53c4cb8fff2
Thanks
