### ISSUE TITLE
Add Datasette

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#648]
**[Datasette](https://datasette.io/)**
**[Github Repo](https://github.com/simonw/datasette)**

**Datasette is a tool for exploring and publishing data. It helps people take data of any shape, analyze and explore it, and publish it as an interactive website and accompanying API.**

**Datasette is aimed at data journalists, museum curators, archivists, local governments, scientists, researchers and anyone else who has data that they wish to share with the world. It is part of a wider ecosystem of [46 tools](https://datasette.io/tools) and [127 plugins](https://datasette.io/plugins) dedicated to making working with structured data as productive as possible.**

**[Vector file](https://datasette.io/static/datasette-logo.svg)**

**Comment by gilbarbara** [comment]
Added in bea0759cf5fbfaad7e92e6032ff9481dd82de561
Thanks
