### ISSUE TITLE
Add Apache Superset

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#649]
**[Apache Superset](https://superset.apache.org/)**
**[Github Repo](https://github.com/apache/superset)**

**Superset is a modern data exploration and data visualization platform. Superset can replace or augment proprietary business intelligence tools for many teams. Superset integrates well with a variety of data sources.**

Superset provides:
- A no-code interface for building charts quickly
- A powerful, web-based SQL Editor for advanced querying
- A lightweight semantic layer for quickly defining custom dimensions and metrics
- Out of the box support for nearly any SQL database or data engine
- A wide array of beautiful visualizations to showcase your data, ranging from simple bar charts to geospatial visualizations
- Lightweight, configurable caching layer to help ease database load
- Highly extensible security roles and authentication options
- An API for programmatic customization
- A cloud-native architecture designed from the ground up for scale

**[Vector file](https://superset.apache.org/img/superset-logo-horiz.svg)**

**Comment by gilbarbara** [comment]
Added in bea0759cf5fbfaad7e92e6032ff9481dd82de561
Thanks
