### ISSUE TITLE
Add Apache Spark

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#650]
**[Apache Spark](https://spark.apache.org/)**

**[Github Repo](https://github.com/apache/spark)**

**Spark is a unified analytics engine for large-scale data processing. It provides high-level APIs in Scala, Java, Python, and R, and an optimized engine that supports general computation graphs for data analysis. It also supports a rich set of higher-level tools including Spark SQL for SQL and DataFrames, pandas API on Spark for pandas workloads, MLlib for machine learning, GraphX for graph processing, and Structured Streaming for stream processing.**

**[Vector file](https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg)**

**Comment by gilbarbara** [comment]
Added in bea0759cf5fbfaad7e92e6032ff9481dd82de561
Thanks
