### ISSUE TITLE
Add Zsh

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#651]
**[Zsh](https://www.zsh.org/)**

**The Z shell (Zsh) is a Unix shell that can be used as an interactive login shell and as a command interpreter for shell scripting. Zsh is an extended Bourne shell with many improvements, including some features of Bash, ksh, and tcsh.** [Wikipedia](https://en.wikipedia.org/wiki/Z_shell)

**[Vector file](https://upload.wikimedia.org/wikipedia/commons/1/1f/Z_Shell_Logo_Color_Horizontal.svg)**

**Comment by gilbarbara** [comment]
Added in cfa9aba939395a50b888e91e29ed1359abc7e986
Thanks
