### ISSUE TITLE
Update Android

### ISSUE THREAD

**Issue by kidonng** [gilbarbara/logos#654]
**Name with link**

[Android](https://www.android.com/)

**Description**

Android branding has been updated recently:

https://blog.google/products/android/modern-look/

**Link to the vector file, preferably from an official source**

- https://upload.wikimedia.org/wikipedia/commons/3/3e/Android_logo_2023.svg
- https://upload.wikimedia.org/wikipedia/commons/2/26/Android_Robot_Head_2023.svg
- https://upload.wikimedia.org/wikipedia/commons/e/ea/Android_logo_2023_%28stacked%29.svg

**Comment by gilbarbara** [comment]
Updated in f133ea921b012052000964e3feb023b57146895b
Thanks
