### ISSUE TITLE
Fix Treehouse logo

### ISSUE THREAD

**Issue by PonomareVlad** [gilbarbara/logos#655]
![Treehouse Logo](https://github.com/gilbarbara/logos/assets/2877584/c72e52ef-076b-4ae3-84da-a1cfac3b49e6)

**Comment by MKRhere** [comment]
The logo in this repo:

<img width=500 src="https://github.com/gilbarbara/logos/assets/19621208/3a12d1c8-b3ec-4f4e-8a46-2f82f036a46a" alt="image">

The correct logo:
<img width=500 src="https://github.com/gilbarbara/logos/assets/19621208/7e571dfb-5be1-4757-bd46-36990b3318a8" alt="image">

For some reason every unofficial version of the Treehouse logo on the internet is broken like this, so I assume at some point an intern uploaded a broken version to their official site and everyone followed it until someone noticed and fixed it. It's our turn to fix it now.

**Comment by PonomareVlad** [comment]
It seems that this logo was the victim of a raster trace 🌚

**Comment by MKRhere** [comment]
Or potentially the result of a broken SVG optimiser.

**Comment by PonomareVlad** [comment]
> Or potentially the result of a broken SVG optimiser.

These glitches say the opposite 🫠

![image](https://github.com/gilbarbara/logos/assets/2877584/e6a372ac-9a82-4ebb-8091-253b4f9e6d7d)

You can check this using services such as http://vectorizer.ai

**Comment by gilbarbara** [comment]
Updated in f133ea921b012052000964e3feb023b57146895b
Thanks
