### ISSUE TITLE
Couple of more logo requests

### ISSUE THREAD

**Issue by gokaygurcan** [gilbarbara/logos#66]
Hello again, 
I came up with another list of requested logos, I hope you won't find them fugly this time ;) 
If you prefer, I can split them up and open an issue for each but this way is cleaner imho. 

- [x] [Cachet](https://raw.githubusercontent.com/cachethq/assets/master/images/logo/Cachet%402x.png)
- [ ] [cheeriojs](https://avatars2.githubusercontent.com/u/7230330?v=3)
- [x] [envato](https://upload.wikimedia.org/wikipedia/en/thumb/f/fe/Envato_Logo.svg/1280px-Envato_Logo.svg.png)
- [ ] [Homebrew](https://raw.githubusercontent.com/Homebrew/homebrew.github.io/master/img/apple-touch-icon-180x180-precomposed.png)
- [x] [Keymetrics](https://keymetrics.io/assets/images/keymetrics-v4.png)
- [x] [Keymetrics v2](https://keymetrics.io/assets/images/Keymetrics-black.png?v=d62b33a81c)
- [x] [knex.js](https://github.com/tgriesser/knex/blob/master/docs/images/knex.png)
- [x] [LevelDB](https://raw.githubusercontent.com/Level/leveldb.org/master/assets/static/img/logo.svg)
- [x] [Mean.io](https://github.com/linnovate/mean-cli/tree/master/img)
- [x] [Modulus](http://blog.modulus.io/img/modulus-logoSmall-gray.png)
- [x] [NodeBots](https://github.com/nodebots/nodebots.io/tree/gh-pages/logo)
- [x] [Origami](https://pbs.twimg.com/profile_images/570277872460242944/M0yxswTJ.png)
- [x] [passportjs](http://passportjs.org/images/logo.svg)
- [x] [pm2](https://cldup.com/PKpktytKH9.png)
- [x] [RethinkDB](https://platzi.com/blog/content/images/2015/03/rethinkdb.png)
- [ ] [scotch.io](https://github.com/scotch-io/scotch-panels/blob/master/website/img/scotch-logo.png)
- [x] [Semantic-UI](http://www.semantic-ui.com/images/logo.png)
- [x] [Square](https://upload.wikimedia.org/wikipedia/commons/7/7d/Square-logo-black.jpeg)
- [x] [StrongLoop](https://strongloop.com/graphics/)
- [x] [StyleCI](https://github.com/StyleCI/Assets/tree/master/logos)
- [x] [taiga.io](https://taiga.io/support/logo/)
- [x] [UIKit](http://getuikit.com/docs/images/logo_uikit_large.svg)
- [x] [v8](https://lh3.googleusercontent.com/GVhelCcnjtNry32N-K7ZcXGRcaxoBzjquGHTzKbXctpE_e_JuxxTJFk_aJCMLZnHFoXHLH-VG7L6LZ1Qc66YjEftCUmPjHoMYTxOQ-0WHtuqddri677H1w7jqMZ88YBdsQ)

Thanks in advance ;)

**Comment by gilbarbara** [comment]
Hey,
Some are in the site already and some I've searched and couldn't find a vector version.
I'll search for the rest.

Thanks

**Comment by gilbarbara** [comment]
Cheerio and Homebrew don't use those images for their products. I'll skip them.

**Comment by gokaygurcan** [comment]
Hey, 
Sorry about Taiga and Passport, I guess I search them as "taiga.io" and "passportjs" and couldn't find in the list. And yes, you're right about cheeriojs and homebrew, let's skip them ;)

Thanks.

**Comment by gilbarbara** [comment]
Some added @ 5ca7e5e67bde37132d476f5eb16d2296a36d609a

**Comment by gilbarbara** [comment]
A few more 6b0c265856f0a8582999c4c151c1156a07724e58

**Comment by gilbarbara** [comment]
Finished f753888db6162ce86d9ecbc0c1fe7abbe5e3f7c8
Thanks

**Comment by gokaygurcan** [comment]
Thanks a lot!
I'll come back with more of them ;)
