### ISSUE TITLE
Add UnJS logo

### ISSUE THREAD

**Issue by Barbapapazes** [gilbarbara/logos#660]
**Name with link**
UnJS

**Description**

**Link to the vector file, preferably from an official source**
https://github.com/unjs/website/blob/main/public/favicon.svg

**Comment by gilbarbara** [comment]
Hey @Barbapapazes 
I usually don't add organization logos, just software and services.

Thanks

**Comment by Barbapapazes** [comment]
Hello!

OK, nice to know. I saw the Apple and Microsoft logos in the collection so I was wondering that I could apply the UnJS one here!
