### ISSUE TITLE
Add uBlock Origin

### ISSUE THREAD

**Issue by Redxtorm** [gilbarbara/logos#667]
**[uBlock Origin](https://github.com/gorhill/uBlock)**

<div align="center">
<img src="https://upload.wikimedia.org/wikipedia/commons/0/05/UBlock_Origin.svg">
</div>

uBlock Origin is a free and open-source browser extension for content filtering, including ad blocking. The extension is available for Chrome, Chromium, Edge, Firefox, Opera, Pale Moon, as well as versions of Safari prior to 13. uBlock Origin has received praise from technology websites and is reported to be much less memory-intensive than other extensions with similar functionality. uBlock Origin's stated purpose is to give users the means to enforce their own (content-filtering) choices. ([Wikipedia](https://en.wikipedia.org/wiki/UBlock_Origin)) 

**[Link to the vector file](https://upload.wikimedia.org/wikipedia/commons/0/05/UBlock_Origin.svg)**

**Comment by gilbarbara** [comment]
Hey @Redxtorm 
Browser extensions and mobile/desktop apps are out of scope for this repo.

Thanks
