### ISSUE TITLE
Add Volar

### ISSUE THREAD

**Issue by manniL** [gilbarbara/logos#670]
**Name with link**

Volar: https://volarjs.dev/

**Description**

> The Embedded Language Tooling Framework.

**Link to the vector file, preferably from an official source**

https://raw.githubusercontent.com/volarjs/docs/main/public/favicon.svg

**Comment by manniL** [comment]
Updated the link to point to the GH raw file

**Comment by gilbarbara** [comment]
Added in 29e8719bf78915c7a82a26a6c203f53c4cb8fff2
Thanks
