### ISSUE TITLE
Add LibGDX

### ISSUE THREAD

**Issue by amalrkc** [gilbarbara/logos#671]
**[LibGDX](https://libgdx.com/)**

<div align="center">
<img src="https://upload.wikimedia.org/wikipedia/commons/f/ff/LibGDX_logo.svg" width="">
</div><br>

libGDX is a free and open-source game-development application framework written in the Java programming language with some C and C++ components for performance dependent code. It allows for the development of desktop and mobile games by using the same code base. It is cross-platform, supporting Windows, Linux, Mac OS X, Android, iOS, BlackBerry and web browsers with WebGL support. ([Wikipedia](https://en.wikipedia.org/wiki/LibGDX))

[Github Repo](https://github.com/libgdx/libgdx)

**[Link to the vector file](https://upload.wikimedia.org/wikipedia/commons/f/ff/LibGDX_logo.svg)**

**Comment by gilbarbara** [comment]
Meh, no legacy stuff
