### ISSUE TITLE
Add Waterfox

### ISSUE THREAD

**Issue by amalrkc** [gilbarbara/logos#676]
<div align="center">
<img src="https://www.waterfox.net/_astro/waterfox-logo-dark.3232b227.svg" width="80%">
</div>

[**Waterfox**](https://www.waterfox.net/)

**Waterfox is a free and open-source web browser and fork of Firefox. It claims to be ethical and user-centric, emphasizing performance and privacy. There are official Waterfox releases for Windows, macOS, and Linux. It was initially created to provide official 64-bit support, back when Firefox was only available for 32-bit systems.**

**Waterfox shares core features and technologies like the Gecko browser engine and support for Firefox Add-ons with Firefox. It is also compatible with Google Chrome and Opera extensions. It disables telemetry and Pocket by default, which are present in Firefox builds. However, it collects technical information about the user's device to update properly. [Wikipedia](https://en.wikipedia.org/wiki/Waterfox)**

[**Github Repo**](https://github.com/WaterfoxCo/Waterfox)

[**Logo on waterfox.net**](https://www.waterfox.net/_astro/waterfox-logo-dark.3232b227.svg)
[**Logo on Wikipedia**](https://en.wikipedia.org/wiki/File:Waterfox_logo_2020_(vectorized).svg)

**Comment by gilbarbara** [comment]
I've never heard of this. Are you using it?

**Comment by amalrkc** [comment]
> I've never heard of this. Are you using it?

No, I do not. It's just a suggestion.

From what I understand, Waterfox allows users to install a wider range of browser extensions than Firefox, including chrome extensions. Here is a quick comparison between the two:

1. Origin and Purpose:

- [Waterfox is a browser based on Firefox code](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)[1](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/). [It was created to be a 64-bit browser and to reduce the amount of telemetry Mozilla received](https://www.reddit.com/r/waterfox/comments/11pswl7/whatre_the_real_benefits_of_using_waterfox_over/)
- [Firefox is an open-source software, which means that any user can access its code](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)

2. Extensions and Add-ons:

- [Waterfox allows users to run any extensions or add-ons they like, including traditional XUL Firefox extensions and NPAPI plug-ins like Java and Silverlight](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)
- [Firefox dropped the traditional Firefox extensions and interface everyone knew when Firefox Quantum and Firefox 57 were released](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)

3. Telemetry:

- [Waterfox is free of telemetry](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)[1](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/).
- [Firefox collects telemetry data and sends it to the developer (Mozilla) to improve the browser](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)
- [However, in Firefox ESR you can easily disable this function and stop your data from being sent to Mozilla](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)
4. Security Updates:

- [The biggest issue with the Waterfox browser is the slow security updates.](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)[ Since Waterfox is based on Firefox ESR, the Waterfox developers have to wait for Mozilla to release the security updates and then work on integrating them into Waterfox](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)
- [Firefox receives security updates on release](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)

- [Some users prefer Waterfox for its configurability and the ability to change settings that aren’t in Firefox](https://www.reddit.com/r/waterfox/comments/11pswl7/whatre_the_real_benefits_of_using_waterfox_over/)

[Please note that the advantages that Waterfox initially had over Firefox may no longer apply](https://helpdeskgeek.com/reviews/firefox-vs-waterfox-which-browser-is-safer-to-use/)

**Comment by gilbarbara** [comment]
Yeah, I'm going to skip this one.
As I mentioned, I don't want to add logos to grow the collection with stuff people won't use.
Relevance is key.
