### ISSUE TITLE
Add Hugging Face

### ISSUE THREAD

**Issue by amalrkc** [gilbarbara/logos#677]
<div align="center">
<img src="https://upload.wikimedia.org/wikipedia/en/4/45/Hugging_Face_logo.svg" width="60%">
</div>
<br><br>

**[Hugging Face](https://huggingface.co/)**

**Hugging Face, Inc.** is a French-American company that develops tools for building applications using machine learning, based in New York City. It is most notable for its transformers library built for natural language processing applications and its platform that allows users to share machine learning models and datasets and showcase their work.

### Transformers Library

The Transformers library is a Python package that contains open-source implementations of transformer models for text, image, and audio tasks. It is compatible with the PyTorch, TensorFlow and JAX deep learning libraries and includes implementations of notable models like BERT and GPT-2. The library was originally called "pytorch-pretrained-bert" which was then renamed to "pytorch-transformers" and finally "transformers."

### Hugging Face Hub

The Hugging Face Hub is a platform (centralized web service) for hosting:

- Git-based code repositories, including discussions and pull requests for projects.
- models, also with Git-based version control;
- datasets, mainly in text, images, and audio;
- web applications ("spaces" and "widgets"), intended for small-scale demos of machine learning applications.

### Other libraries

In addition to Transformers and the Hugging Face Hub, the Hugging Face ecosystem contains libraries for other tasks, such as dataset processing ("Datasets"), model evaluation ("Evaluate"), simulation ("Simulate"), machine learning demos ("Gradio").

[Wikipedia](https://en.wikipedia.org/wiki/Hugging_Face)

[Github Profile](https://github.com/huggingface)

**[Link to the vector file](https://upload.wikimedia.org/wikipedia/en/4/45/Hugging_Face_logo.svg)**

**Comment by gilbarbara** [comment]
Added in 52addcaa18dfecb4df77f3ee0753dca6b98187ad
Thanks
