### ISSUE TITLE
Add Bluesky

### ISSUE THREAD

**Issue by snazzyfox** [gilbarbara/logos#682]
**Bluesky**

Bluesky (bsky.app) is a social media platform, previously owned by twitter but since became a spinoff. It's now run by former twitter execs. It has a few million users today and is fairly active, and many of its users consider it an alternative to Twitter/X.

Their logo was released about a week ago.

**Link to the vector file, preferably from an official source**

[Press info](https://blueskyweb.xyz/blog/press-faq) (link to press kit is near bottom)

[Direct link to logos in official Google Drive](https://drive.google.com/file/d/1oRjS9EQjkHpOTUZzgyVuFbmX2PZQgWfw/view?usp=drive_link)

**Comment by OzzyCzech** [comment]
The URL of Bluesky [Google drive has changed](https://drive.google.com/drive/folders/16mlJPfWNnc6jj-3vGZ88SFysIY13GBp0)

You can also use my repository to get [latest Bluesky logo](https://github.com/OzzyCzech/bluesky-icon)

**Comment by gilbarbara** [comment]
Added in 92bb74e98bca1ea1ad794442676ebc4e75038adc
Thanks
