### ISSUE TITLE
Add htmx

### ISSUE THREAD

**Issue by asm0dey** [gilbarbara/logos#686]
**Name with link**

htmx

https://htmx.org

**Description**

**Link to the vector file, preferably from an official source**

Unofficial SVG: https://plugins.jetbrains.com/files/20588/418328/icon/pluginIcon.svg

Official logo 1: https://github.com/bigskysoftware/htmx/blob/master/www/static/img/htmx_logo.1.png

Official logo 2: https://github.com/bigskysoftware/htmx/blob/master/www/static/img/htmx_logo.2.png

**Comment by gilbarbara** [comment]
Added in 92bb74e98bca1ea1ad794442676ebc4e75038adc
Thanks
