### ISSUE TITLE
Add FIDO Alliance

### ISSUE THREAD

**Issue by amalrkc** [gilbarbara/logos#688]
<div align="center">
<img src="https://fidoalliance.org/wp-content/themes/frost/assets/images/fido-logo-v2.svg" width="40%">
</div>

**[fidoalliance.org](https://fidoalliance.org/)**

The FIDO ("Fast IDentity Online") Alliance is an open industry association launched in February 2013 whose stated mission is to develop and promote authentication standards that "help reduce the world’s over-reliance on passwords". FIDO addresses the lack of interoperability among devices that use strong authentication and reduces the problems users face creating and remembering multiple usernames and passwords.

FIDO supports a full range of authentication technologies, including biometrics such as fingerprint and iris scanners, voice and facial recognition, as well as existing solutions and communications standards, such as Trusted Platform Modules (TPM), USB security tokens, embedded Secure Elements (eSE), smart cards, and near-field communication (NFC). The USB security token device may be used to authenticate using a simple password (e.g. four-digit PIN) or by pressing a button. The specifications emphasize a device-centric model. Authentication over the wire happens using public-key cryptography. The user's device registers the user to a server by registering a public key. To authenticate the user, the device signs a challenge from the server using the private key that it holds. The keys on the device are unlocked by a local user gesture such as a biometric or pressing a button.

FIDO provides two types of user experiences depending on which protocol is used. Both protocols define a common interface at the client for whatever local authentication method the user exercises. [Wikipedia](https://en.wikipedia.org/wiki/FIDO_Alliance)

**[Link to the vector file, preferably from an official source](https://fidoalliance.org/wp-content/themes/frost/assets/images/fido-logo-v2.svg)**

**Comment by amalrkc** [comment]
### Also see,

https://en.wikipedia.org/wiki/WebAuthn

https://webauthn.guide/

https://auth0.com/blog/webauthn-a-short-introduction/

https://www.freecodecamp.org/news/intro-to-webauthn/

### **WebAuthn Demos:**
https://webauthn.io/

https://webauthn.me/

https://passage.1password.com/demo

https://webauthn.dodo.dev/passwordless

https://webauthn.passwordless.id/demos/playground.html

**Comment by gilbarbara** [comment]
Hey
They have a weird logo usage policy that required signing up, so I'll skip it for now.
