### ISSUE TITLE
Add CockroachDB

### ISSUE THREAD

**Issue by tomy0000000** [gilbarbara/logos#691]
**Name with link**: [CockroachDB](https://github.com/cockroachdb/cockroach)

**Description**: CockroachDB (sometimes shortened as CRDB) is a free and open source distributed SQL database built on a transactional and strongly-consistent key-value store. It is backed by PebbleDB (a RocksDB/LevelDB-inspired KV store) and uses the Raft distributed consensus algorithm to ensure consistency.

**Link to the vector file, preferably from an official source**: Only PNG is available on [GitHub](https://github.com/cockroachdb/cockroach) and their company [site](https://github.com/cockroachdb/cockroach).

**Comment by gilbarbara** [comment]
Hey @tomy0000000 
I've looked into adding it before, but since there's no SVG it's a deal breaker.
