### ISSUE TITLE
Add Adobe Inc. Logo

### ISSUE THREAD

**Issue by ehricson-falcon-swo** [gilbarbara/logos#695]
![image](https://github.com/gilbarbara/logos/assets/56329385/1306a0f6-b554-4255-802b-d5205a2ad9ec)

Adobe Corporate Logo

**Description**
Adobe Inc. formerly Adobe Systems Incorporated, is an American company.

**Link to the vector file, preferably from an official source**
[https://upload.wikimedia.org/wikipedia/commons/6/6e/Adobe_Corporate_logo.svg]()

**Comment by gilbarbara** [comment]
Added in 92bb74e98bca1ea1ad794442676ebc4e75038adc
Thanks
