### ISSUE TITLE
Add Apache Cordova logo

### ISSUE THREAD

**Issue by aloisdg** [gilbarbara/logos#7]
As you add PhoneGap, you may want to add Apache Cordova.

You can find theirs logos in the [artwork's part](https://cordova.apache.org/artwork.html) of their website.

New logo :

![Apache Cordova Logo](https://cordova.apache.org/images/logo_full.png)

**Comment by gilbarbara** [comment]
I would love to but I couldn't find the logo in vector/svg. I'll look for it again!

**Comment by gilbarbara** [comment]
Added 7fa588e448310510e3b4cc116e9d9236a90f0ced

**Comment by aloisdg** [comment]
Great! Thank you!
