### ISSUE TITLE
Add X (Twitter)

### ISSUE THREAD

**Issue by IgnaceMaes** [gilbarbara/logos#702]
**Name with link**

X: [x.com](https://x.com/)

**Description**

The new Twitter logo.

**Link to the vector file, preferably from an official source**

Direct SVG for convenience: https://gist.github.com/IgnaceMaes/744cd9cf41ec6acf46fc8f4e9f370f86

From: https://about.x.com/en/who-we-are/brand-toolkit

**Comment by gilbarbara** [comment]
Added in 92bb74e98bca1ea1ad794442676ebc4e75038adc
Thanks
