### ISSUE TITLE
daisyUI - logo update

### ISSUE THREAD

**Issue by Avaray** [gilbarbara/logos#708]
Currently your repository contains very old `daisyUI` logo.

There are two new official logotypes available on [official website](https://daisyui.com/).   
You need to click right mouse button on logo in header to download them.

Direct links:  
https://img.daisyui.com/images/daisyui-logo/daisyui-logomark.svg
https://img.daisyui.com/images/daisyui-logo/daisyui-logotype.svg

**Comment by gilbarbara** [comment]
Updated in 5c1d9713d5ae7b26a5fd26cbd2927d359c328fb5
Thanks
