### ISSUE TITLE
Add Typora

### ISSUE THREAD

**Issue by zhuozhiyongde** [gilbarbara/logos#710]
**Name with link**

[Typora](https://typora.io/)

**Description**

A widely used WYSIWYG markdown editor.

**Link to the vector file, preferably from an official source**

https://github.com/cworld1/theme-astro-pure/blob/main/src/icons/typora.svg

(It was drawn by me.)

**Comment by gilbarbara** [comment]
Hey @zhuozhiyongde 

Browser extensions and mobile/desktop apps are out of the scope of this repo.

Thanks!
