### ISSUE TITLE
Add Warp

### ISSUE THREAD

**Issue by zhuozhiyongde** [gilbarbara/logos#711]
**Name with link**

[Warp](https://www.warp.dev/)

**Description**

Warp is the terminal reimagined with AI and collaborative tools for better productivity.

**Link to the vector file, preferably from an official source**

https://github.com/cworld1/theme-astro-pure/blob/main/src/icons/warp.svg

**Comment by gilbarbara** [comment]
Hey @zhuozhiyongde 

Browser extensions and mobile/desktop apps are out of the scope of this repo.

Thanks!
