### ISSUE TITLE
Update Biome JS logo

### ISSUE THREAD

**Issue by OzzyCzech** [gilbarbara/logos#714]
**Name with link**
[Biome JS](https://biomejs.dev/)

**Description**
They have brand new logo, please update  

**Link to the vector file, preferably from an official source**
https://biomejs.dev/_astro/logo-light-transparent.D-4iVN_O.svg

**Comment by gilbarbara** [comment]
Updated in 5c1d9713d5ae7b26a5fd26cbd2927d359c328fb5
Thanks
