### ISSUE TITLE
Slidev logo styles wrong

### ISSUE THREAD

**Issue by antfu** [gilbarbara/logos#719]
Hi, thanks for maintaining this repo, it has been super helpful!

I am the creator the Slidev, and I recently noticed the included Logo of Slidev seems have broken style.

It should look like (https://sli.dev, https://sli.dev/logo.svg):
<img width="281" alt="Screenshot 2024-09-18 at 19 49 04" src="https://github.com/user-attachments/assets/985995bd-6489-4783-9485-2fc268b2cb71">

But in this collection it becomes:
<img width="375" alt="Screenshot 2024-09-18 at 19 50 46" src="https://github.com/user-attachments/assets/8bff3bd1-e6ac-4e3d-a542-ec08ca6adaff">

I don't know why it happened, but could you help fix it? I am here if you need any help (I have the original design in Figma). Thank you!

**Comment by gilbarbara** [comment]
Hey @antfu 
Oops! sorry!
Updating it now

**Comment by gilbarbara** [comment]
Updated in 5c1d9713d5ae7b26a5fd26cbd2927d359c328fb5
Thanks

**Comment by antfu** [comment]
Thank you!
