### ISSUE TITLE
Update `UnoCSS` logo style

### ISSUE THREAD

**Issue by zyyv** [gilbarbara/logos#720]
**Name with link**
UnoCSS

**Description**
Hi, i am UnoCSS team member, and I am sure that the previous logo svg is outdated, and the previous logo is extremely unfriendly in dark mode, please update it when you have free time.
Related to #707

|  before  |  after  |
| --  |  -- |
|  ![old](https://raw.githubusercontent.com/zyyv/logos/de8fdaf0ce10dc9f0c41e7f0612da5d2d36f4e74/logos/unocss.svg)  |  ![new](https://raw.githubusercontent.com/zyyv/logos/0757c4d9daf9fa8b9177c0bcc6d69d02e3ea81eb/logos/unocss.svg) |

**Link to the vector file, preferably from an official source**
Official Link: https://unocss.dev/logo.svg

**Comment by gilbarbara** [comment]
Updated in 5c1d9713d5ae7b26a5fd26cbd2927d359c328fb5
Thanks
