### ISSUE TITLE
Add Apple podcast

### ISSUE THREAD

**Issue by ryoppippi** [gilbarbara/logos#724]
**Name with link**
https://marketing.services.apple/apple-podcasts-identity-guidelines

https://apple.ent.box.com/s/03awr22q9ee9xtlppvubvwy66oxn7dwa
**Description**

**Link to the vector file, preferably from an official source**

**Comment by gilbarbara** [comment]
Hey @ryoppippi 

Browser extensions and mobile/desktop apps are out of the scope of this repo.

Thanks

**Comment by ryoppippi** [comment]
Oh okay! Thanks.
