### ISSUE TITLE
Add vscode-neovim logo

### ISSUE THREAD

**Issue by ryoppippi** [gilbarbara/logos#728]
**Name with link**
https://github.com/vscode-neovim/vscode-neovim/blob/master/images/icon.png
**Description**

**Link to the vector file, preferably from an official source**

**Comment by gilbarbara** [comment]
Hey @ryoppippi 
We need a vector.

**Comment by ryoppippi** [comment]
@gilbarbara 
Oh, sorry.
I forgot it is png!
I'll close it
