### ISSUE TITLE
Add zenn

### ISSUE THREAD

**Issue by ryoppippi** [gilbarbara/logos#729]
**Name with link**

https://zenn.dev
guideline: https://zenn.dev/mediakit
download link: https://static.zenn.studio/images/mediakit/zenn-logo.zip

**Description**
zenn is a Japanese media for developers, like dev.to
**Link to the vector file, preferably from an official source**

**Comment by gilbarbara** [comment]
Hey @ryoppippi 
We usually don't add regional tools since a website in japanese wouldn't mean anything to most users.

Thanks
