### ISSUE TITLE
Issue: vscode icon has wired non-opacity in the middle

### ISSUE THREAD

**Issue by ryoppippi** [gilbarbara/logos#730]
The VSCode icon in this repo
![vsc](https://raw.githubusercontent.com/gilbarbara/logos/refs/heads/main/logos/visual-studio-code.svg)
	
The VSCode icon in [vscode-icons](https://github.com/vscode-icons/vscode-icons)

![vsc](https://raw.githubusercontent.com/vscode-icons/vscode-icons/refs/heads/master/icons/file_type_vscode.svg)

There is this kind of diff in `visual-studio.svg`

**Comment by gilbarbara** [comment]
I just opened the SVG, and there's nothing in the middle.
https://cdn.svgporn.com/logos/visual-studio-code.svg
I've used the official logo from https://code.visualstudio.com/brand
