### ISSUE TITLE
Add AWS Architecture Icons (full set)

### ISSUE THREAD

**Issue by loozhengyuan** [gilbarbara/logos#733]
This is a logo request to update/augment the current set of AWS architecture icons in the logo set which can be retrieved from: https://aws.amazon.com/architecture/icons/

Related: https://github.com/iconify/icon-sets/issues/152

**Comment by gilbarbara** [comment]
Hey @loozhengyuan 

This repo is a curated list of logos, so we don't plan to add every logo.

While we have the most significant AWS logos, adding/maintaining the whole set isn't feasible.
Do you have any specific logos that you want to add? I could add an extra few.

**Comment by gilbarbara** [comment]
Yeah, I think so too.
Good luck!
