### ISSUE TITLE
Why not rename the repo?

### ISSUE THREAD

**Issue by Mr21** [gilbarbara/logos#76]
Hi :)

Why not rename the repo like your page http://svgporn.com/ ?
And the old url github.com/gilbarbara/logos will redirect to the new one.

**Comment by gilbarbara** [comment]
hey!

The svgporn domain was a little inside joke and I'll probably change it soon. I've already purchased http://svgmania.com/
So I think it's best to keep the repo name simple and constant.

[s]

**Comment by Mr21** [comment]
Ok ok as you want :+1: 
I just thought maybe you didn't know about the GitHub's redirection.

**Comment by gilbarbara** [comment]
:grimacing: :+1:

**Comment by styfle** [comment]
@gilbarbara I think svgmania.com is a much better name.
It will also avoid the domain from being blocked at work 😆
