### ISSUE TITLE
CSS3's logo is not the correct one

### ISSUE THREAD

**Issue by Mr21** [gilbarbara/logos#78]
Hi :)

Here, http://www.w3.org/html/logo/ you can see the real CSS3's logo.
The CSS is one of many parts of the HTML5, it's not at the same level, so it's incorrect to draw it on the same way.

Maybe you can reuse this: http://fontawesome.io/icon/css3/

What do you think?

**Comment by gilbarbara** [comment]
hey

I can add the simple 3 logo but the css badge is a universal symbol for the language.

**Comment by Mr21** [comment]
Really? I can't find it, where did you read that?

**Comment by gilbarbara** [comment]
[the interwebs](https://www.google.com.br/search?q=css&safe=off&es_sm=119&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIieKM5rSPxwIVRnE-Ch1AYgEv&biw=1280&bih=871#safe=off&tbm=isch&q=css+3)

**Comment by gilbarbara** [comment]
added 17d52cd909f698fd1f55c35cdccefc3224202269
