### ISSUE TITLE
Suggestion: jQuery icon only

### ISSUE THREAD

**Issue by rctneil** [gilbarbara/logos#80]
How about the jQuery logo without the text?

Oh and possibly add Microsoft Edge?

**Comment by gilbarbara** [comment]
hey,
I thought about using only the jquery logomark but isn't clearly recognizable.

About Microsoft Edge: 
![MS Edge](http://realfunny.net/uploads/700xNxthe_mystery_of_microsoft_edge_is_uncovered_by_scooby_doo_and_friends._6006506695.jpg.pagespeed.ic.sprd9EnOHQ.jpg)

**Comment by rctneil** [comment]
Hmm, I still think the logomark on it's own could be useful in some cases.  Edge has a different (yet suspiciously similar) logo so I think it's eligible to be included.

**Comment by gilbarbara** [comment]
Added MS Edge f209440ba434258ed6d944c649804c506ad9525f
