### ISSUE TITLE
middleman logo

### ISSUE THREAD

**Issue by flexbox** [gilbarbara/logos#82]
Hello there,

Middleman is a static site generator (like jekyll used for blogs) for ruby lovers.

Here is the image
https://middlemanapp.com/images/middleman-logo.svg

Cheers!

**Comment by gilbarbara** [comment]
Hey!
It's already in my backlog! :+1:

**Comment by flexbox** [comment]
Great news !
I close the issue

**Comment by gilbarbara** [comment]
Added a9ddfa5988b9034ca727c35d474fec73575b89f5

Cheers
