### ISSUE TITLE
iMessage

### ISSUE THREAD

**Issue by rctneil** [gilbarbara/logos#83]
Could you add a logo for Apple's iMessage?

**Comment by bondMR** [comment]
Neil Tonge.
How do you do.
Yes , I can be the logo design . Do you have been looking for a designer of " iMessage " logo design Co., Ltd. apple?

Awkward and sorry in English .
By " Google Translate "

**Comment by gilbarbara** [comment]
Hey,

I think this is a little out of boundaries for this collection, at least for now. If I start to add mobile icons it's a whole new world.

Cheers

**Comment by rctneil** [comment]
I only thought about this as you ahve other social network icons. I was thinking the one like this: https://upload.wikimedia.org/wikipedia/en/5/51/IMessage_Icon.png

No worries if you still think innappropriate.
