### ISSUE TITLE
Knockout logo

### ISSUE THREAD

**Issue by jlnabais** [gilbarbara/logos#84]
Hello there,

Knockout is a JavaScript library that helps creating rich, responsive display and editor user interfaces with a clean underlying data model.

Project home:
http://knockoutjs.com/index.html

Logo:
http://knockoutjs.com/img/ko-logo.png

Cheers!

**Comment by gilbarbara** [comment]
Hey,
I searched for their logo before but I couldn't find a vector version or at least a decent png without shadows.
As soon as I find one I'll definitely add it!

Cheers

**Comment by luisrudge** [comment]
I have some files that may help you.

Here's the logo without shadows:
![ko-logo_vectorized](https://cloud.githubusercontent.com/assets/941075/9619696/f57706f8-50e8-11e5-8411-25e9c7446a9a.png)

Here's a zip with `.eps`, `.svg`, `.png` and `.pdf`.
http://1drv.ms/1VuWVUt

**Comment by gilbarbara** [comment]
Awesome!
Thanks @luisrudge 
Added 7dc1b8b6910a254efec43994f348d06ffc3d683b

**Comment by luisrudge** [comment]
Awesome!
