### ISSUE TITLE
JetBrains products logos

### ISSUE THREAD

**Issue by jlnabais** [gilbarbara/logos#89]
Hello there,

Anyway to have JetBrains products logos? You already have the brand logo.

Project (products) home:
https://www.jetbrains.com/products.html

Cheers!

**Comment by jlnabais** [comment]
http://ikame.vn/img/intellij.svg
https://www.jetbrains.com/clion/documentation/docs/logo_CLion.svg

**Comment by jlnabais** [comment]
https://www.jetbrains.com/company/press/materials.html

**Comment by gilbarbara** [comment]
Added e6da55bd87a881cf5bbac4dc7044a6510b7c3cc4
Thanks
