### ISSUE TITLE
AutoIt

### ISSUE THREAD

**Issue by softwarespot** [gilbarbara/logos#96]
Unable to locate a svg from https://www.autoitscript.com/site/

**Comment by softwarespot** [comment]
Here is an svg from the author of the language. Just rename the extension from png to svg.

![autoit_11](https://cloud.githubusercontent.com/assets/5333690/10101826/aeb42e58-63a3-11e5-98ac-b82985590ea4.png)

**Comment by softwarespot** [comment]
Here is a svg >> https://www.autoitscript.com/forum/cdn/images/logo_autoit_210x72.svg

**Comment by softwarespot** [comment]
https://cloud.githubusercontent.com/assets/5333690/10101826/aeb42e58-63a3-11e5-98ac-b82985590ea4.png

Just rename png to svg.

**Comment by gilbarbara** [comment]
@softwarespot What changed from your previous comment?

**Comment by softwarespot** [comment]
Well I deleted it because the [forum](https://www.autoitscript.com/forum/} now uses a svg for the main icon, so I decided to link to that instead of my png "hack". But I realised after I posted it, that the svg I sent you previously (which is from the site owner) had a background. I was being an idiot basically!

**Comment by softwarespot** [comment]
Here is a direct link https://www.autoitscript.com/images/logo_autoit_back_210x72.svg

**Comment by gilbarbara** [comment]
Added 8b5d6c0f1bfccf6a1b53b0a0757dbbee01358705
Thanks
