### ISSUE TITLE
New Opera logo

### ISSUE THREAD

**Issue by rctneil** [gilbarbara/logos#97]
How about adding the new Opera logo?

http://blogs.opera.com/news/2015/09/opera-new-logo-and-brand-identity/

**Comment by AGodinez** [comment]
something like the logo? XD
https://gist.github.com/AGodinez/01853e7315b91ed56c2d

**Comment by gilbarbara** [comment]
Added 65317564c34066b0b996441d49228ae9ba329c03

Thanks
