### ISSUE TITLE
Hexo, Brunch, Thimble

### ISSUE THREAD

**Issue by AGodinez** [gilbarbara/logos#98]
Hello!
Would be nice to have some these logos :smile: 

**Hexo**: http://hexo.io/
A fast, simple & powerful blog framework 
SVG: https://gist.github.com/AGodinez/fe9219d80adedf0812ba
Suggested Tags: blog framework, node.js, cli

**Brunch**: http://brunch.io/
Ultra-fast HTML5 build tool 
SVG: https://camo.githubusercontent.com/a60ec6a86bf0d6b2c07ce2f39033a81443830f73/687474703a2f2f6272756e63682e696f2f696d616765732f7376672f6272756e63682e737667
Suggested Tags: html5, build tool, cli

**Mozilla Thimble**: https://thimble.mozilla.org/
An online code editor.
SVG: https://thimble.webmaker.org/img/thimble-logo.svg
Suggested Tags: code editor, playground

PD: I made changes because I saw that the broccoli is already added haha

**Comment by gilbarbara** [comment]
Added 65317564c34066b0b996441d49228ae9ba329c03
Thanks! :)
