### ISSUE TITLE
WebRTC Logo

### ISSUE THREAD

**Issue by cpustar** [gilbarbara/logos#99]
It would be nice to have the WebRTC logo:

![Image of WebRTC](http://www.webrtc.org/_/rsrc/1318870658554/config/customLogo.gif?revision=8)
![Image of WebRTC](http://cdn.sixrevisions.com/0370-01_webrtc_logo_thumbnail.png)

**Comment by gilbarbara** [comment]
Added 2e1c1c4f79a2a67cf8bb253a6d3bf4fc2fa8d396
Thanks
